/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AlltoAllvQuantGroupedMatMul_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AlltoAllvQuantGroupedMatMul_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_AlltoAllvQuantGroupedMatMul_c.h"
namespace ge {
namespace es {

struct AlltoAllvQuantGroupedMatMulOutput {
  EsTensorHolder gmm_y;
  EsTensorHolder mm_y;
  EsTensorHolder permute_out;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   gmm_x
 *   gmm_weight
 *   gmm_x_scale
 *   gmm_weight_scale
 *   send_counts_tensor
 *   recv_counts_tensor
 *   mm_x
 *   mm_weight
 *   mm_x_scale
 *   mm_weight_scale
 */
inline AlltoAllvQuantGroupedMatMulOutput AlltoAllvQuantGroupedMatMul(const EsTensorLike & gmm_x, const EsTensorLike & gmm_weight, const EsTensorLike & gmm_x_scale, const EsTensorLike & gmm_weight_scale, const EsTensorLike & send_counts_tensor, const EsTensorLike & recv_counts_tensor, const EsTensorLike & mm_x, const EsTensorLike & mm_weight, const EsTensorLike & mm_x_scale, const EsTensorLike & mm_weight_scale, const char * group, int64_t ep_world_size, const std::vector<int64_t> & send_counts, const std::vector<int64_t> & recv_counts, int64_t gmm_x_quant_mode, int64_t gmm_weight_quant_mode, bool trans_gmm_weight=false, bool trans_mm_weight=false, bool permute_out_flag=false, int64_t mm_x_quant_mode=0, int64_t mm_weight_quant_mode=0, int64_t group_size=0, int64_t y_dtype=28, int64_t mm_dtype=28, const char * comm_mode="ai_cpu") {
  auto *owner_graph_builder = ResolveBuilder(gmm_x, gmm_weight, gmm_x_scale, gmm_weight_scale, send_counts_tensor, recv_counts_tensor, mm_x, mm_weight, mm_x_scale, mm_weight_scale);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsAlltoAllvQuantGroupedMatMul(gmm_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gmm_weight.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gmm_x_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gmm_weight_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), send_counts_tensor.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), recv_counts_tensor.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mm_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mm_weight.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mm_x_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mm_weight_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), group, ep_world_size, send_counts.data(), static_cast<int64_t>(send_counts.size()), recv_counts.data(), static_cast<int64_t>(recv_counts.size()), gmm_x_quant_mode, gmm_weight_quant_mode, trans_gmm_weight, trans_mm_weight, permute_out_flag, mm_x_quant_mode, mm_weight_quant_mode, group_size, y_dtype, mm_dtype, comm_mode);
  return {out.gmm_y, out.mm_y, out.permute_out};
}
}  // namespace es
}  // namespace ge
#endif
