/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AttentionUpdate_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AttentionUpdate_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_AttentionUpdate_c.h"
namespace ge {
namespace es {

struct AttentionUpdateOutput {
  EsTensorHolder output;
  EsTensorHolder lse_m;
};
inline AttentionUpdateOutput AttentionUpdate(const std::vector<EsTensorHolder> & lse, const std::vector<EsTensorHolder> & go, int64_t update_type, int64_t sp) {
  auto esb_lse = TensorsToEsCTensorHolders(lse);
  auto esb_go = TensorsToEsCTensorHolders(go);
  auto out = EsAttentionUpdate(esb_lse.data(), static_cast<int64_t>(esb_lse.size()), esb_go.data(), static_cast<int64_t>(esb_go.size()), update_type, sp);
  return {out.output, out.lse_m};
}
}  // namespace es
}  // namespace ge
#endif
