/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AlltoAllAllGatherBatchMatMul_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AlltoAllAllGatherBatchMatMul_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_AlltoAllAllGatherBatchMatMul_c.h"
namespace ge {
namespace es {

struct AlltoAllAllGatherBatchMatMulOutput {
  EsTensorHolder y1;
  EsTensorHolder y2;
  EsTensorHolder y3;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   weight
 *   bias
 */
inline AlltoAllAllGatherBatchMatMulOutput AlltoAllAllGatherBatchMatMul(const EsTensorLike & x, const EsTensorLike & weight, const EsTensorLike & bias, const char * group_ep, const char * group_tp, int64_t ep_world_size, int64_t tp_world_size, int64_t x_shard_type=0, int64_t act_type=0, bool transpose_weight=false, bool output_y2_flag=false, bool output_y3_flag=false) {
  auto *owner_graph_builder = ResolveBuilder(x, weight, bias);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsAlltoAllAllGatherBatchMatMul(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), weight.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bias.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), group_ep, group_tp, ep_world_size, tp_world_size, x_shard_type, act_type, transpose_weight, output_y2_flag, output_y3_flag);
  return {out.y1, out.y2, out.y3};
}
}  // namespace es
}  // namespace ge
#endif
