/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AlltoAllMatmul_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AlltoAllMatmul_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder *y;
  EsCTensorHolder *all2all_out;
} EsAlltoAllMatmulOutput;
EsAlltoAllMatmulOutput EsAlltoAllMatmul(EsCTensorHolder *x1, EsCTensorHolder *x2, EsCTensorHolder *bias, EsCTensorHolder *x1_scale, EsCTensorHolder *x2_scale, EsCTensorHolder *comm_scale, EsCTensorHolder *x1_offset, EsCTensorHolder *x2_offset, const char *group, int64_t world_size, const int64_t *all2all_axes, int64_t all2all_axes_num, int64_t y_dtype, int64_t x1_quant_mode, int64_t x2_quant_mode, int64_t comm_quant_mode, int64_t x1_quant_dtype, int64_t comm_quant_dtype, bool transpose_x1, bool transpose_x2, int64_t group_size, const char *comm_mode, bool alltoall_out_flag);
#ifdef __cplusplus
}
#endif
#endif
