/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_FFNToAttention_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_FFNToAttention_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_FFNToAttention_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   session_ids
 *   micro_batch_ids
 *   token_ids
 *   expert_offsets
 *   actual_token_num
 *   attn_rank_table
 */
inline EsTensorHolder FFNToAttention(const EsTensorLike & x, const EsTensorLike & session_ids, const EsTensorLike & micro_batch_ids, const EsTensorLike & token_ids, const EsTensorLike & expert_offsets, const EsTensorLike & actual_token_num, const EsTensorLike & attn_rank_table, const char * group, int64_t world_size, const std::vector<int64_t> & token_info_table_shape, const std::vector<int64_t> & token_data_shape) {
  auto *owner_graph_builder = ResolveBuilder(x, session_ids, micro_batch_ids, token_ids, expert_offsets, actual_token_num, attn_rank_table);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsFFNToAttention(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), session_ids.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), micro_batch_ids.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), token_ids.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), expert_offsets.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), actual_token_num.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), attn_rank_table.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), group, world_size, token_info_table_shape.data(), static_cast<int64_t>(token_info_table_shape.size()), token_data_shape.data(), static_cast<int64_t>(token_data_shape.size()));
  return out;
}
}  // namespace es
}  // namespace ge
#endif
