/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_FusedCausalConv1d_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_FusedCausalConv1d_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_FusedCausalConv1d_c.h"
namespace ge {
namespace es {

struct FusedCausalConv1dOutput {
  EsTensorHolder ref_conv_states;
  EsTensorHolder y;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   weight
 *   conv_states
 *   query_start_loc
 *   cache_indices
 *   initial_state_mode
 *   bias
 *   num_accepted_tokens
 *   num_computed_tokens
 *   block_idx_first_scheduled_token
 *   block_idx_last_scheduled_token
 *   initial_state_idx
 */
inline FusedCausalConv1dOutput FusedCausalConv1d(const EsTensorLike & x, const EsTensorLike & weight, const EsTensorLike & conv_states, const EsTensorLike & query_start_loc=nullptr, const EsTensorLike & cache_indices=nullptr, const EsTensorLike & initial_state_mode=nullptr, const EsTensorLike & bias=nullptr, const EsTensorLike & num_accepted_tokens=nullptr, const EsTensorLike & num_computed_tokens=nullptr, const EsTensorLike & block_idx_first_scheduled_token=nullptr, const EsTensorLike & block_idx_last_scheduled_token=nullptr, const EsTensorLike & initial_state_idx=nullptr, int64_t activation_mode=0, int64_t pad_slot_id=-1, int64_t run_mode=0, int64_t max_query_len=-1, int64_t residual_connection=1, int64_t block_size=128, int64_t conv_mode=0) {
  auto *owner_graph_builder = ResolveBuilder(x, weight, conv_states, query_start_loc, cache_indices, initial_state_mode, bias, num_accepted_tokens, num_computed_tokens, block_idx_first_scheduled_token, block_idx_last_scheduled_token, initial_state_idx);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsFusedCausalConv1d(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), weight.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), conv_states.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), query_start_loc.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), cache_indices.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), initial_state_mode.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bias.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), num_accepted_tokens.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), num_computed_tokens.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), block_idx_first_scheduled_token.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), block_idx_last_scheduled_token.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), initial_state_idx.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), activation_mode, pad_slot_id, run_mode, max_query_len, residual_connection, block_size, conv_mode);
  return {out.ref_conv_states, out.y};
}
}  // namespace es
}  // namespace ge
#endif
