/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_InplaceMatmulAllReduceAddRmsNorm_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_InplaceMatmulAllReduceAddRmsNorm_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_InplaceMatmulAllReduceAddRmsNorm_c.h"
namespace ge {
namespace es {

struct InplaceMatmulAllReduceAddRmsNormOutput {
  EsTensorHolder ref_residual;
  EsTensorHolder norm_out;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x1
 *   x2
 *   bias
 *   residual
 *   gamma
 *   antiquant_scale
 *   antiquant_offset
 *   dequant_scale
 */
inline InplaceMatmulAllReduceAddRmsNormOutput InplaceMatmulAllReduceAddRmsNorm(const EsTensorLike & x1, const EsTensorLike & x2, const EsTensorLike & bias, const EsTensorLike & residual, const EsTensorLike & gamma, const EsTensorLike & antiquant_scale, const EsTensorLike & antiquant_offset, const EsTensorLike & dequant_scale, const char * group, const char * reduce_op="sum", bool is_trans_a=false, bool is_trans_b=false, int64_t comm_turn=0, int64_t antiquant_group_size=0, float epsilon=0.000001) {
  auto *owner_graph_builder = ResolveBuilder(x1, x2, bias, residual, gamma, antiquant_scale, antiquant_offset, dequant_scale);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsInplaceMatmulAllReduceAddRmsNorm(x1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bias.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), residual.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gamma.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), antiquant_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), antiquant_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), dequant_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), group, reduce_op, is_trans_a, is_trans_b, comm_turn, antiquant_group_size, epsilon);
  return {out.ref_residual, out.norm_out};
}
}  // namespace es
}  // namespace ge
#endif
