/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_InplaceFusedCausalConv1d_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_InplaceFusedCausalConv1d_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder *ref_conv_states;
  EsCTensorHolder *ref_x;
} EsInplaceFusedCausalConv1dOutput;
EsInplaceFusedCausalConv1dOutput EsInplaceFusedCausalConv1d(EsCTensorHolder *x, EsCTensorHolder *weight, EsCTensorHolder *conv_states, EsCTensorHolder *query_start_loc, EsCTensorHolder *cache_indices, EsCTensorHolder *initial_state_mode, EsCTensorHolder *bias, EsCTensorHolder *num_accepted_tokens, EsCTensorHolder *num_computed_tokens, EsCTensorHolder *block_idx_first_scheduled_token, EsCTensorHolder *block_idx_last_scheduled_token, EsCTensorHolder *initial_state_idx, int64_t activation_mode, int64_t pad_slot_id, int64_t run_mode, int64_t max_query_len, int64_t residual_connection, int64_t block_size, int64_t conv_mode);
#ifdef __cplusplus
}
#endif
#endif
