/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_IncreFlashAttention_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_IncreFlashAttention_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_IncreFlashAttention_c.h"
namespace ge {
namespace es {

inline EsTensorHolder IncreFlashAttention(const EsTensorLike & query, const std::vector<EsTensorHolder> & key, const std::vector<EsTensorHolder> & value, const EsTensorLike & pse_shift, const EsTensorLike & atten_mask, const EsTensorLike & actual_seq_lengths, const EsTensorLike & dequant_scale1, const EsTensorLike & quant_scale1, const EsTensorLike & dequant_scale2, const EsTensorLike & quant_scale2, const EsTensorLike & quant_offset2, const EsTensorLike & antiquant_scale, const EsTensorLike & antiquant_offset, const EsTensorLike & block_table, const EsTensorLike & kv_padding_size, int64_t num_heads, float scale_value=1.000000, const char * input_layout="BSH", int64_t num_key_value_heads=1, int64_t block_size=0, int64_t inner_precise=1) {
  auto *owner_graph_builder = ResolveBuilder(query, key, value, pse_shift, atten_mask, actual_seq_lengths, dequant_scale1, quant_scale1, dequant_scale2, quant_scale2, quant_offset2, antiquant_scale, antiquant_offset, block_table, kv_padding_size);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto esb_key = TensorsToEsCTensorHolders(key);
  auto esb_value = TensorsToEsCTensorHolders(value);
  auto out = EsIncreFlashAttention(query.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), esb_key.data(), static_cast<int64_t>(esb_key.size()), esb_value.data(), static_cast<int64_t>(esb_value.size()), pse_shift.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), atten_mask.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), actual_seq_lengths.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), dequant_scale1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_scale1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), dequant_scale2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_scale2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_offset2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), antiquant_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), antiquant_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), block_table.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), kv_padding_size.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), num_heads, scale_value, input_layout, num_key_value_heads, block_size, inner_precise);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
