/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_IncreFlashAttention_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_IncreFlashAttention_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif
EsCTensorHolder *EsIncreFlashAttention(EsCTensorHolder *query, EsCTensorHolder **key, int64_t key_num, EsCTensorHolder **value, int64_t value_num, EsCTensorHolder *pse_shift, EsCTensorHolder *atten_mask, EsCTensorHolder *actual_seq_lengths, EsCTensorHolder *dequant_scale1, EsCTensorHolder *quant_scale1, EsCTensorHolder *dequant_scale2, EsCTensorHolder *quant_scale2, EsCTensorHolder *quant_offset2, EsCTensorHolder *antiquant_scale, EsCTensorHolder *antiquant_offset, EsCTensorHolder *block_table, EsCTensorHolder *kv_padding_size, int64_t num_heads, float scale_value, const char *input_layout, int64_t num_key_value_heads, int64_t block_size, int64_t inner_precise);
#ifdef __cplusplus
}
#endif
#endif
