/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_KvRmsNormRopeCache_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_KvRmsNormRopeCache_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_KvRmsNormRopeCache_c.h"
namespace ge {
namespace es {

struct KvRmsNormRopeCacheOutput {
  EsTensorHolder ref_k_cache;
  EsTensorHolder ref_ckv_cache;
  EsTensorHolder k_rope;
  EsTensorHolder c_kv;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   kv
 *   gamma
 *   cos
 *   sin
 *   index
 *   k_cache
 *   ckv_cache
 *   k_rope_scale
 *   c_kv_scale
 *   k_rope_offset
 *   c_kv_offset
 *   v
 */
inline KvRmsNormRopeCacheOutput KvRmsNormRopeCache(const EsTensorLike & kv, const EsTensorLike & gamma, const EsTensorLike & cos, const EsTensorLike & sin, const EsTensorLike & index, const EsTensorLike & k_cache, const EsTensorLike & ckv_cache, const EsTensorLike & k_rope_scale=nullptr, const EsTensorLike & c_kv_scale=nullptr, const EsTensorLike & k_rope_offset=nullptr, const EsTensorLike & c_kv_offset=nullptr, const EsTensorLike & v=nullptr, float epsilon=0.000010, const char * cache_mode="Norm", bool is_output_kv=false) {
  auto *owner_graph_builder = ResolveBuilder(kv, gamma, cos, sin, index, k_cache, ckv_cache, k_rope_scale, c_kv_scale, k_rope_offset, c_kv_offset, v);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsKvRmsNormRopeCache(kv.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gamma.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), cos.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), sin.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), index.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), k_cache.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), ckv_cache.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), k_rope_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), c_kv_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), k_rope_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), c_kv_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), v.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), epsilon, cache_mode, is_output_kv);
  return {out.ref_k_cache, out.ref_ckv_cache, out.k_rope, out.c_kv};
}
}  // namespace es
}  // namespace ge
#endif
