/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_KvRmsNormRopeCache_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_KvRmsNormRopeCache_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder *ref_k_cache;
  EsCTensorHolder *ref_ckv_cache;
  EsCTensorHolder *k_rope;
  EsCTensorHolder *c_kv;
} EsKvRmsNormRopeCacheOutput;
EsKvRmsNormRopeCacheOutput EsKvRmsNormRopeCache(EsCTensorHolder *kv, EsCTensorHolder *gamma, EsCTensorHolder *cos, EsCTensorHolder *sin, EsCTensorHolder *index, EsCTensorHolder *k_cache, EsCTensorHolder *ckv_cache, EsCTensorHolder *k_rope_scale, EsCTensorHolder *c_kv_scale, EsCTensorHolder *k_rope_offset, EsCTensorHolder *c_kv_offset, EsCTensorHolder *v, float epsilon, const char *cache_mode, bool is_output_kv);
#ifdef __cplusplus
}
#endif
#endif
