/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeGatingTopK_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeGatingTopK_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_MoeGatingTopK_c.h"
namespace ge {
namespace es {

struct MoeGatingTopKOutput {
  EsTensorHolder y;
  EsTensorHolder expert_idx;
  EsTensorHolder out;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   bias
 */
inline MoeGatingTopKOutput MoeGatingTopK(const EsTensorLike & x, const EsTensorLike & bias, int64_t k, int64_t k_group=1, int64_t group_count=1, int64_t group_select_mode=0, int64_t renorm=0, int64_t norm_type=0, bool out_flag=false, float routed_scaling_factor=1.000000, float eps=0.000000) {
  auto *owner_graph_builder = ResolveBuilder(x, bias);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsMoeGatingTopK(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bias.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), k, k_group, group_count, group_select_mode, renorm, norm_type, out_flag, routed_scaling_factor, eps);
  return {out.y, out.expert_idx, out.out};
}
}  // namespace es
}  // namespace ge
#endif
