/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeDistributeCombineAddRmsNorm_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeDistributeCombineAddRmsNorm_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder *y;
  EsCTensorHolder *rstd;
  EsCTensorHolder *x;
} EsMoeDistributeCombineAddRmsNormOutput;
EsMoeDistributeCombineAddRmsNormOutput EsMoeDistributeCombineAddRmsNorm(EsCTensorHolder *expand_x, EsCTensorHolder *expert_ids, EsCTensorHolder *assist_info_for_combine, EsCTensorHolder *ep_send_counts, EsCTensorHolder *expert_scales, EsCTensorHolder *residual_x, EsCTensorHolder *gamma, EsCTensorHolder *tp_send_counts, EsCTensorHolder *x_active_mask, EsCTensorHolder *activation_scale, EsCTensorHolder *weight_scale, EsCTensorHolder *group_list, EsCTensorHolder *expand_scales, EsCTensorHolder *shared_expert_x, EsCTensorHolder *elastic_info, EsCTensorHolder *ori_x, EsCTensorHolder *const_expert_alpha_1, EsCTensorHolder *const_expert_alpha_2, EsCTensorHolder *const_expert_v, const char *group_ep, int64_t ep_world_size, int64_t ep_rank_id, int64_t moe_expert_num, const char *group_tp, int64_t tp_world_size, int64_t tp_rank_id, int64_t expert_shard_type, int64_t shared_expert_num, int64_t shared_expert_rank_num, int64_t global_bs, int64_t out_dtype, int64_t comm_quant_mode, int64_t group_list_type, const char *comm_alg, float norm_eps, int64_t zero_expert_num, int64_t copy_expert_num, int64_t const_expert_num);
#ifdef __cplusplus
}
#endif
#endif
