/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeDistributeCombineV3_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeDistributeCombineV3_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_MoeDistributeCombineV3_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   context
 *   expand_x
 *   expert_ids
 *   assist_info_for_combine
 *   ep_send_counts
 *   expert_scales
 *   tp_send_counts
 *   x_active_mask
 *   activation_scale
 *   weight_scale
 *   group_list
 *   expand_scales
 *   shared_expert_x
 *   elastic_info
 *   ori_x
 *   const_expert_alpha_1
 *   const_expert_alpha_2
 *   const_expert_v
 *   performance_info
 */
inline EsTensorHolder MoeDistributeCombineV3(const EsTensorLike & context, const EsTensorLike & expand_x, const EsTensorLike & expert_ids, const EsTensorLike & assist_info_for_combine, const EsTensorLike & ep_send_counts, const EsTensorLike & expert_scales, const EsTensorLike & tp_send_counts, const EsTensorLike & x_active_mask, const EsTensorLike & activation_scale, const EsTensorLike & weight_scale, const EsTensorLike & group_list, const EsTensorLike & expand_scales, const EsTensorLike & shared_expert_x, const EsTensorLike & elastic_info, const EsTensorLike & ori_x, const EsTensorLike & const_expert_alpha_1, const EsTensorLike & const_expert_alpha_2, const EsTensorLike & const_expert_v, const EsTensorLike & performance_info, int64_t ep_world_size, int64_t ep_rank_id, int64_t moe_expert_num, int64_t ccl_buffer_size, int64_t tp_world_size=0, int64_t tp_rank_id=0, int64_t expert_shard_type=0, int64_t shared_expert_num=1, int64_t shared_expert_rank_num=0, int64_t global_bs=0, int64_t out_dtype=0, int64_t comm_quant_mode=0, int64_t group_list_type=0, const char * comm_alg="", int64_t zero_expert_num=0, int64_t copy_expert_num=0, int64_t const_expert_num=0) {
  auto *owner_graph_builder = ResolveBuilder(context, expand_x, expert_ids, assist_info_for_combine, ep_send_counts, expert_scales, tp_send_counts, x_active_mask, activation_scale, weight_scale, group_list, expand_scales, shared_expert_x, elastic_info, ori_x, const_expert_alpha_1, const_expert_alpha_2, const_expert_v, performance_info);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsMoeDistributeCombineV3(context.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), expand_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), expert_ids.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), assist_info_for_combine.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), ep_send_counts.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), expert_scales.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), tp_send_counts.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x_active_mask.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), activation_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), weight_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), group_list.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), expand_scales.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), shared_expert_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), elastic_info.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), ori_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), const_expert_alpha_1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), const_expert_alpha_2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), const_expert_v.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), performance_info.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), ep_world_size, ep_rank_id, moe_expert_num, ccl_buffer_size, tp_world_size, tp_rank_id, expert_shard_type, shared_expert_num, shared_expert_rank_num, global_bs, out_dtype, comm_quant_mode, group_list_type, comm_alg, zero_expert_num, copy_expert_num, const_expert_num);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
