/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeInitRoutingV3_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeInitRoutingV3_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder *expanded_x;
  EsCTensorHolder *expanded_row_idx;
  EsCTensorHolder *expert_tokens_count_or_cumsum;
  EsCTensorHolder *expanded_scale;
} EsMoeInitRoutingV3Output;
EsMoeInitRoutingV3Output EsMoeInitRoutingV3(EsCTensorHolder *x, EsCTensorHolder *expert_idx, EsCTensorHolder *scale, EsCTensorHolder *offset, int64_t active_num, int64_t expert_capacity, int64_t expert_num, int64_t drop_pad_mode, int64_t expert_tokens_num_type, bool expert_tokens_num_flag, int64_t quant_mode, const int64_t *active_expert_range, int64_t active_expert_range_num, int64_t row_idx_type);
#ifdef __cplusplus
}
#endif
#endif
