/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeReRouting_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeReRouting_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_MoeReRouting_c.h"
namespace ge {
namespace es {

struct MoeReRoutingOutput {
  EsTensorHolder permute_tokens;
  EsTensorHolder permute_per_token_scales;
  EsTensorHolder permute_token_idx;
  EsTensorHolder expert_token_num;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   tokens
 *   expert_token_num_per_rank
 *   per_token_scales
 */
inline MoeReRoutingOutput MoeReRouting(const EsTensorLike & tokens, const EsTensorLike & expert_token_num_per_rank, const EsTensorLike & per_token_scales=nullptr, int64_t expert_token_num_type=1, int64_t idx_type=0) {
  auto *owner_graph_builder = ResolveBuilder(tokens, expert_token_num_per_rank, per_token_scales);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsMoeReRouting(tokens.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), expert_token_num_per_rank.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), per_token_scales.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), expert_token_num_type, idx_type);
  return {out.permute_tokens, out.permute_per_token_scales, out.permute_token_idx, out.expert_token_num};
}
}  // namespace es
}  // namespace ge
#endif
