/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MatmulAllReduce_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MatmulAllReduce_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif
EsCTensorHolder *EsMatmulAllReduce(EsCTensorHolder *x1, EsCTensorHolder *x2, EsCTensorHolder *bias, EsCTensorHolder *x3, EsCTensorHolder *antiquant_scale, EsCTensorHolder *antiquant_offset, EsCTensorHolder *dequant_scale, EsCTensorHolder *pertoken_scale, EsCTensorHolder *comm_quant_scale_1, EsCTensorHolder *comm_quant_scale_2, const char *group, const char *reduce_op, bool is_trans_a, bool is_trans_b, int64_t comm_turn, int64_t antiquant_group_size, int64_t group_size, int64_t y_dtype, int64_t comm_quant_mode, const char *comm_mode);
#ifdef __cplusplus
}
#endif
#endif
