/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeInitRoutingV3_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeInitRoutingV3_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_MoeInitRoutingV3_c.h"
namespace ge {
namespace es {

struct MoeInitRoutingV3Output {
  EsTensorHolder expanded_x;
  EsTensorHolder expanded_row_idx;
  EsTensorHolder expert_tokens_count_or_cumsum;
  EsTensorHolder expanded_scale;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   expert_idx
 *   scale
 *   offset
 */
inline MoeInitRoutingV3Output MoeInitRoutingV3(const EsTensorLike & x, const EsTensorLike & expert_idx, const EsTensorLike & scale=nullptr, const EsTensorLike & offset=nullptr, int64_t active_num=-1, int64_t expert_capacity=-1, int64_t expert_num=-1, int64_t drop_pad_mode=0, int64_t expert_tokens_num_type=0, bool expert_tokens_num_flag=false, int64_t quant_mode=-1, const std::vector<int64_t> & active_expert_range={}, int64_t row_idx_type=0) {
  auto *owner_graph_builder = ResolveBuilder(x, expert_idx, scale, offset);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsMoeInitRoutingV3(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), expert_idx.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), active_num, expert_capacity, expert_num, drop_pad_mode, expert_tokens_num_type, expert_tokens_num_flag, quant_mode, active_expert_range.data(), static_cast<int64_t>(active_expert_range.size()), row_idx_type);
  return {out.expanded_x, out.expanded_row_idx, out.expert_tokens_count_or_cumsum, out.expanded_scale};
}
}  // namespace es
}  // namespace ge
#endif
