/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeFinalizeRoutingV2Grad_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeFinalizeRoutingV2Grad_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_MoeFinalizeRoutingV2Grad_c.h"
namespace ge {
namespace es {

struct MoeFinalizeRoutingV2GradOutput {
  EsTensorHolder grad_expanded_x;
  EsTensorHolder grad_scales;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   grad_y
 *   expanded_row_idx
 *   expanded_x
 *   scales
 *   expert_idx
 *   bias
 */
inline MoeFinalizeRoutingV2GradOutput MoeFinalizeRoutingV2Grad(const EsTensorLike & grad_y, const EsTensorLike & expanded_row_idx, const EsTensorLike & expanded_x=nullptr, const EsTensorLike & scales=nullptr, const EsTensorLike & expert_idx=nullptr, const EsTensorLike & bias=nullptr, int64_t drop_pad_mode=0, int64_t active_num=0, int64_t expert_num=0, int64_t expert_capacity=0) {
  auto *owner_graph_builder = ResolveBuilder(grad_y, expanded_row_idx, expanded_x, scales, expert_idx, bias);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsMoeFinalizeRoutingV2Grad(grad_y.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), expanded_row_idx.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), expanded_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scales.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), expert_idx.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bias.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), drop_pad_mode, active_num, expert_num, expert_capacity);
  return {out.grad_expanded_x, out.grad_scales};
}
}  // namespace es
}  // namespace ge
#endif
