/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MatmulAlltoAll_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MatmulAlltoAll_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_MatmulAlltoAll_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x1
 *   x2
 *   bias
 *   x1_scale
 *   x2_scale
 *   comm_scale
 *   x1_offset
 *   x2_offset
 */
inline EsTensorHolder MatmulAlltoAll(const EsTensorLike & x1, const EsTensorLike & x2, const EsTensorLike & bias, const EsTensorLike & x1_scale, const EsTensorLike & x2_scale, const EsTensorLike & comm_scale, const EsTensorLike & x1_offset, const EsTensorLike & x2_offset, const char * group, int64_t world_size, const std::vector<int64_t> & all2all_axes={-1, -2}, int64_t y_dtype=28, int64_t x1_quant_mode=0, int64_t x2_quant_mode=0, int64_t comm_quant_mode=0, int64_t comm_quant_dtype=28, bool transpose_x1=false, bool transpose_x2=false, int64_t group_size=0, const char * comm_mode="ai_cpu") {
  auto *owner_graph_builder = ResolveBuilder(x1, x2, bias, x1_scale, x2_scale, comm_scale, x1_offset, x2_offset);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsMatmulAlltoAll(x1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bias.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x1_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), comm_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x1_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), group, world_size, all2all_axes.data(), static_cast<int64_t>(all2all_axes.size()), y_dtype, x1_quant_mode, x2_quant_mode, comm_quant_mode, comm_quant_dtype, transpose_x1, transpose_x2, group_size, comm_mode);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
