/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeUpdateExpert_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeUpdateExpert_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder *balanced_expert_ids;
  EsCTensorHolder *balanced_active_mask;
} EsMoeUpdateExpertOutput;
EsMoeUpdateExpertOutput EsMoeUpdateExpert(EsCTensorHolder *expert_ids, EsCTensorHolder *eplb_table, EsCTensorHolder *expert_scales, EsCTensorHolder *pruning_threshold, EsCTensorHolder *active_mask, int64_t local_rank_id, int64_t world_size, int64_t balance_mode);
#ifdef __cplusplus
}
#endif
#endif
