/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeUpdateExpert_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MoeUpdateExpert_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_MoeUpdateExpert_c.h"
namespace ge {
namespace es {

struct MoeUpdateExpertOutput {
  EsTensorHolder balanced_expert_ids;
  EsTensorHolder balanced_active_mask;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   expert_ids
 *   eplb_table
 *   expert_scales
 *   pruning_threshold
 *   active_mask
 */
inline MoeUpdateExpertOutput MoeUpdateExpert(const EsTensorLike & expert_ids, const EsTensorLike & eplb_table, const EsTensorLike & expert_scales=nullptr, const EsTensorLike & pruning_threshold=nullptr, const EsTensorLike & active_mask=nullptr, int64_t local_rank_id=-1, int64_t world_size=-1, int64_t balance_mode=0) {
  auto *owner_graph_builder = ResolveBuilder(expert_ids, eplb_table, expert_scales, pruning_threshold, active_mask);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsMoeUpdateExpert(expert_ids.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), eplb_table.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), expert_scales.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), pruning_threshold.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), active_mask.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), local_rank_id, world_size, balance_mode);
  return {out.balanced_expert_ids, out.balanced_active_mask};
}
}  // namespace es
}  // namespace ge
#endif
