/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_PromptFlashAttention_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_PromptFlashAttention_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_PromptFlashAttention_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   query
 *   key
 *   value
 *   pse_shift
 *   atten_mask
 *   actual_seq_lengths
 *   actual_seq_lengths_kv
 *   deq_scale1
 *   quant_scale1
 *   deq_scale2
 *   quant_scale2
 *   quant_offset2
 */
inline EsTensorHolder PromptFlashAttention(const EsTensorLike & query, const EsTensorLike & key, const EsTensorLike & value, const EsTensorLike & pse_shift, const EsTensorLike & atten_mask, const EsTensorLike & actual_seq_lengths, const EsTensorLike & actual_seq_lengths_kv, const EsTensorLike & deq_scale1, const EsTensorLike & quant_scale1, const EsTensorLike & deq_scale2, const EsTensorLike & quant_scale2, const EsTensorLike & quant_offset2, int64_t num_heads, float scale_value=1.000000, int64_t pre_tokens=214748647, int64_t next_tokens=0, const char * input_layout="BSH", int64_t num_key_value_heads=0, int64_t sparse_mode=0, int64_t inner_precise=1) {
  auto *owner_graph_builder = ResolveBuilder(query, key, value, pse_shift, atten_mask, actual_seq_lengths, actual_seq_lengths_kv, deq_scale1, quant_scale1, deq_scale2, quant_scale2, quant_offset2);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsPromptFlashAttention(query.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), key.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), value.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), pse_shift.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), atten_mask.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), actual_seq_lengths.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), actual_seq_lengths_kv.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), deq_scale1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_scale1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), deq_scale2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_scale2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_offset2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), num_heads, scale_value, pre_tokens, next_tokens, input_layout, num_key_value_heads, sparse_mode, inner_precise);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
