/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_QkvRmsNormRopeCache_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_QkvRmsNormRopeCache_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_QkvRmsNormRopeCache_c.h"
namespace ge {
namespace es {

struct QkvRmsNormRopeCacheOutput {
  EsTensorHolder ref_q_out;
  EsTensorHolder ref_k_cache;
  EsTensorHolder ref_v_cache;
  EsTensorHolder q_out_before_quant;
  EsTensorHolder k_out_before_quant;
  EsTensorHolder v_out_before_quant;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   qkv
 *   q_gamma
 *   k_gamma
 *   cos
 *   sin
 *   index
 *   q_out
 *   k_cache
 *   v_cache
 *   k_scale
 *   v_scale
 *   k_offset
 *   v_offset
 */
inline QkvRmsNormRopeCacheOutput QkvRmsNormRopeCache(const EsTensorLike & qkv, const EsTensorLike & q_gamma, const EsTensorLike & k_gamma, const EsTensorLike & cos, const EsTensorLike & sin, const EsTensorLike & index, const EsTensorLike & q_out, const EsTensorLike & k_cache, const EsTensorLike & v_cache, const EsTensorLike & k_scale, const EsTensorLike & v_scale, const EsTensorLike & k_offset, const EsTensorLike & v_offset, const std::vector<int64_t> & qkv_size, const std::vector<int64_t> & head_nums, float epsilon=0.000001, const char * cache_mode="PA_NZ", bool is_output_qkv=false) {
  auto *owner_graph_builder = ResolveBuilder(qkv, q_gamma, k_gamma, cos, sin, index, q_out, k_cache, v_cache, k_scale, v_scale, k_offset, v_offset);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsQkvRmsNormRopeCache(qkv.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), q_gamma.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), k_gamma.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), cos.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), sin.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), index.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), q_out.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), k_cache.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), v_cache.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), k_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), v_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), k_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), v_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), qkv_size.data(), static_cast<int64_t>(qkv_size.size()), head_nums.data(), static_cast<int64_t>(head_nums.size()), epsilon, cache_mode, is_output_qkv);
  return {out.ref_q_out, out.ref_k_cache, out.ref_v_cache, out.q_out_before_quant, out.k_out_before_quant, out.v_out_before_quant};
}
}  // namespace es
}  // namespace ge
#endif
