/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_QkvRmsNormRopeCache_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_QkvRmsNormRopeCache_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder *ref_q_out;
  EsCTensorHolder *ref_k_cache;
  EsCTensorHolder *ref_v_cache;
  EsCTensorHolder *q_out_before_quant;
  EsCTensorHolder *k_out_before_quant;
  EsCTensorHolder *v_out_before_quant;
} EsQkvRmsNormRopeCacheOutput;
EsQkvRmsNormRopeCacheOutput EsQkvRmsNormRopeCache(EsCTensorHolder *qkv, EsCTensorHolder *q_gamma, EsCTensorHolder *k_gamma, EsCTensorHolder *cos, EsCTensorHolder *sin, EsCTensorHolder *index, EsCTensorHolder *q_out, EsCTensorHolder *k_cache, EsCTensorHolder *v_cache, EsCTensorHolder *k_scale, EsCTensorHolder *v_scale, EsCTensorHolder *k_offset, EsCTensorHolder *v_offset, const int64_t *qkv_size, int64_t qkv_size_num, const int64_t *head_nums, int64_t head_nums_num, float epsilon, const char *cache_mode, bool is_output_qkv);
#ifdef __cplusplus
}
#endif
#endif
