/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ScatterPaKvCache_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ScatterPaKvCache_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_ScatterPaKvCache_c.h"
namespace ge {
namespace es {

struct ScatterPaKvCacheOutput {
  EsTensorHolder ref_key_cache;
  EsTensorHolder ref_value_cache;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   key
 *   key_cache
 *   slot_mapping
 *   value
 *   value_cache
 *   compress_lens
 *   compress_seq_offset
 *   seq_lens
 */
inline ScatterPaKvCacheOutput ScatterPaKvCache(const EsTensorLike & key, const EsTensorLike & key_cache, const EsTensorLike & slot_mapping, const EsTensorLike & value, const EsTensorLike & value_cache, const EsTensorLike & compress_lens=nullptr, const EsTensorLike & compress_seq_offset=nullptr, const EsTensorLike & seq_lens=nullptr, const char * cache_mode="Norm", const char * scatter_mode="None", const std::vector<int64_t> & strides={1, 1}, const std::vector<int64_t> & offsets={0, 0}) {
  auto *owner_graph_builder = ResolveBuilder(key, key_cache, slot_mapping, value, value_cache, compress_lens, compress_seq_offset, seq_lens);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsScatterPaKvCache(key.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), key_cache.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), slot_mapping.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), value.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), value_cache.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), compress_lens.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), compress_seq_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), seq_lens.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), cache_mode, scatter_mode, strides.data(), static_cast<int64_t>(strides.size()), offsets.data(), static_cast<int64_t>(offsets.size()));
  return {out.ref_key_cache, out.ref_value_cache};
}
}  // namespace es
}  // namespace ge
#endif
