/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/
#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_transformer_OPS_CPP_H
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_transformer_OPS_CPP_H


/** Unsupported ops and reasons: 
 */
#include "es_AllGatherMatmul.h"
#include "es_AllGatherMatmulV2.h"
#include "es_AlltoAllAllGatherBatchMatMul.h"
#include "es_AlltoAllMatmul.h"
#include "es_AlltoAllvGroupedMatMul.h"
#include "es_AlltoAllvQuantGroupedMatMul.h"
#include "es_ApplyRotaryPosEmb.h"
#include "es_AttentionToFFN.h"
#include "es_AttentionUpdate.h"
#include "es_AttentionWorkerCombine.h"
#include "es_BatchMatMulReduceScatterAlltoAll.h"
#include "es_DistributeBarrier.h"
#include "es_DistributeBarrierExtend.h"
#include "es_FFNToAttention.h"
#include "es_FusedCausalConv1d.h"
#include "es_GatherPaKvCache.h"
#include "es_GroupedMatMulAllReduce.h"
#include "es_GroupedMatMulAlltoAllv.h"
#include "es_IncreFlashAttention.h"
#include "es_InplaceFusedCausalConv1d.h"
#include "es_InplaceMatmulAllReduceAddRmsNorm.h"
#include "es_InterleaveRope.h"
#include "es_KvRmsNormRopeCache.h"
#include "es_MaskedCausalConv1d.h"
#include "es_MatmulAllReduce.h"
#include "es_MatmulAllReduceAddRmsNorm.h"
#include "es_MatmulAlltoAll.h"
#include "es_MatmulReduceScatter.h"
#include "es_MatmulReduceScatterV2.h"
#include "es_MhcPost.h"
#include "es_MhcSinkhorn.h"
#include "es_MoeComputeExpertTokens.h"
#include "es_MoeDistributeCombine.h"
#include "es_MoeDistributeCombineAddRmsNorm.h"
#include "es_MoeDistributeCombineSetup.h"
#include "es_MoeDistributeCombineTeardown.h"
#include "es_MoeDistributeCombineV2.h"
#include "es_MoeDistributeCombineV3.h"
#include "es_MoeDistributeDispatch.h"
#include "es_MoeDistributeDispatchSetup.h"
#include "es_MoeDistributeDispatchTeardown.h"
#include "es_MoeDistributeDispatchV2.h"
#include "es_MoeDistributeDispatchV3.h"
#include "es_MoeFinalizeRoutingV2.h"
#include "es_MoeFinalizeRoutingV2Grad.h"
#include "es_MoeGatingTopK.h"
#include "es_MoeGatingTopKSoftmax.h"
#include "es_MoeGatingTopKSoftmaxV2.h"
#include "es_MoeInitRouting.h"
#include "es_MoeInitRoutingQuantV2.h"
#include "es_MoeInitRoutingV2.h"
#include "es_MoeInitRoutingV2Grad.h"
#include "es_MoeInitRoutingV3.h"
#include "es_MoeReRouting.h"
#include "es_MoeUpdateExpert.h"
#include "es_PromptFlashAttention.h"
#include "es_QkvRmsNormRopeCache.h"
#include "es_QuantAllReduce.h"
#include "es_QuantGroupedMatMulAlltoAllv.h"
#include "es_QuantReduceScatter.h"
#include "es_RotaryPositionEmbedding.h"
#include "es_RotaryPositionEmbeddingGrad.h"
#include "es_ScatterPaCache.h"
#include "es_ScatterPaKvCache.h"
#include "es_TransposeD.h"
#endif  // AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_transformer_OPS_CPP_H
