#ifndef ACL_EXTEND_VERSION_H
#define ACL_EXTEND_VERSION_H

#define ACL_EXTEND_VERSION_STR "9.1.0"
#define ACL_EXTEND_MAJOR 9
#define ACL_EXTEND_MINOR 1
#define ACL_EXTEND_PATCH 0
#define ACL_EXTEND_PRERELEASE ""
#define ACL_EXTEND_VERSION_NUM ((9 * 10000000) + (1 * 100000) + (0 * 1000))
#define ACL_EXTEND_TIMESTAMP 0

#endif /* ACL_EXTEND_VERSION_H */
