#ifndef DFLOW-EXECUTOR_VERSION_H
#define DFLOW-EXECUTOR_VERSION_H

#define DFLOW_VERSION_STR "9.1.0"
#define DFLOW_MAJOR 9
#define DFLOW_MINOR 1
#define DFLOW_PATCH 0
#define DFLOW_PRERELEASE ""
#define DFLOW_VERSION_NUM ((9 * 10000000) + (1 * 100000) + (0 * 1000))
#define DFLOW_TIMESTAMP 0

#endif /* DFLOW-EXECUTOR_VERSION_H */
