#ifndef GE-COMPILER_VERSION_H
#define GE-COMPILER_VERSION_H

#define GE_COMPILER_VERSION_STR "9.1.0"
#define GE_COMPILER_MAJOR 9
#define GE_COMPILER_MINOR 1
#define GE_COMPILER_PATCH 0
#define GE_COMPILER_PRERELEASE ""
#define GE_COMPILER_VERSION_NUM ((9 * 10000000) + (1 * 100000) + (0 * 1000))
#define GE_COMPILER_TIMESTAMP 0

#endif /* GE-COMPILER_VERSION_H */
