#ifndef GE-EXECUTOR_VERSION_H
#define GE-EXECUTOR_VERSION_H

#define GE_EXECUTOR_VERSION_STR "9.1.0"
#define GE_EXECUTOR_MAJOR 9
#define GE_EXECUTOR_MINOR 1
#define GE_EXECUTOR_PATCH 0
#define GE_EXECUTOR_PRERELEASE ""
#define GE_EXECUTOR_VERSION_NUM ((9 * 10000000) + (1 * 100000) + (0 * 1000))
#define GE_EXECUTOR_TIMESTAMP 0

#endif /* GE-EXECUTOR_VERSION_H */
