#ifndef GRAPH_AUTOFUSION_VERSION_H
#define GRAPH_AUTOFUSION_VERSION_H

#define GRAPH_AUTOFUSION_VERSION_STR "9.1.0"
#define GRAPH_AUTOFUSION_MAJOR 9
#define GRAPH_AUTOFUSION_MINOR 1
#define GRAPH_AUTOFUSION_PATCH 0
#define GRAPH_AUTOFUSION_PRERELEASE ""
#define GRAPH_AUTOFUSION_VERSION_NUM ((9 * 10000000) + (1 * 100000) + (0 * 1000))
#define GRAPH_AUTOFUSION_TIMESTAMP 0

#endif /* GRAPH_AUTOFUSION_VERSION_H */
