#ifndef METADEF_VERSION_H
#define METADEF_VERSION_H

#define METADEF_VERSION_STR "9.1.0"
#define METADEF_MAJOR 9
#define METADEF_MINOR 1
#define METADEF_PATCH 0
#define METADEF_PRERELEASE ""
#define METADEF_VERSION_NUM ((9 * 10000000) + (1 * 100000) + (0 * 1000))

#endif /* METADEF_VERSION_H */
