#ifndef OAM_TOOLS_VERSION_H
#define OAM_TOOLS_VERSION_H

#define OPS_BASE_VERSION_STR "9.1.0"
#define OPS_BASE_MAJOR 9
#define OPS_BASE_MINOR 1
#define OPS_BASE_PATCH 0
#define OPS_BASE_PRERELEASE ""
#define OPS_BASE_VERSION_NUM ((9 * 10000000) + (1 * 100000) + (0 * 1000))
#define OPS_BASE_TIMESTAMP 0

#endif /* OAM_TOOLS_VERSION_H */
