#ifndef OPS_TRANSFORMER_VERSION_H
#define OPS_TRANSFORMER_VERSION_H

#define OPS_TRANSFORMER_VERSION_STR "9.1.0"
#define OPS_TRANSFORMER_MAJOR 9
#define OPS_TRANSFORMER_MINOR 1
#define OPS_TRANSFORMER_PATCH 0
#define OPS_TRANSFORMER_PRERELEASE ""
#define OPS_TRANSFORMER_VERSION_NUM ((9 * 10000000) + (1 * 100000) + (0 * 1000))
#define OPS_TRANSFORMER_TIMESTAMP 0

#endif /* OPS_TRANSFORMER_VERSION_H */
