/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ApplyAdam_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ApplyAdam_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_ApplyAdam_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   var
 *   m
 *   v
 *   beta1_power
 *   beta2_power
 *   lr
 *   beta1
 *   beta2
 *   epsilon
 *   grad
 */
inline EsTensorHolder ApplyAdam(const EsTensorLike & var, const EsTensorLike & m, const EsTensorLike & v, const EsTensorLike & beta1_power, const EsTensorLike & beta2_power, const EsTensorLike & lr, const EsTensorLike & beta1, const EsTensorLike & beta2, const EsTensorLike & epsilon, const EsTensorLike & grad, bool use_locking=false, bool use_nesterov=false) {
  auto *owner_graph_builder = ResolveBuilder(var, m, v, beta1_power, beta2_power, lr, beta1, beta2, epsilon, grad);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsApplyAdam(var.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), m.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), v.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta1_power.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta2_power.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), lr.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), epsilon.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), grad.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), use_locking, use_nesterov);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
