/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AdvanceStep_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AdvanceStep_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_AdvanceStep_c.h"
namespace ge {
namespace es {

struct AdvanceStepOutput {
  EsTensorHolder ref_input_tokens;
  EsTensorHolder ref_input_positions;
  EsTensorHolder ref_seq_lens;
  EsTensorHolder ref_slot_mapping;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   input_tokens
 *   sampled_token_ids
 *   input_positions
 *   seq_lens
 *   slot_mapping
 *   block_tables
 *   spec_token
 *   accepted_num
 */
inline AdvanceStepOutput AdvanceStep(const EsTensorLike & input_tokens, const EsTensorLike & sampled_token_ids, const EsTensorLike & input_positions, const EsTensorLike & seq_lens, const EsTensorLike & slot_mapping, const EsTensorLike & block_tables, const EsTensorLike & spec_token, const EsTensorLike & accepted_num, int64_t num_seqs, int64_t num_queries, int64_t block_size) {
  auto *owner_graph_builder = ResolveBuilder(input_tokens, sampled_token_ids, input_positions, seq_lens, slot_mapping, block_tables, spec_token, accepted_num);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsAdvanceStep(input_tokens.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), sampled_token_ids.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input_positions.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), seq_lens.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), slot_mapping.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), block_tables.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), spec_token.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), accepted_num.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), num_seqs, num_queries, block_size);
  return {out.ref_input_tokens, out.ref_input_positions, out.ref_seq_lens, out.ref_slot_mapping};
}
}  // namespace es
}  // namespace ge
#endif
