/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AdamApplyOne_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AdamApplyOne_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_AdamApplyOne_c.h"
namespace ge {
namespace es {

struct AdamApplyOneOutput {
  EsTensorHolder output0;
  EsTensorHolder output1;
  EsTensorHolder output2;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   input0
 *   input1
 *   input2
 *   input3
 *   input4
 *   mul0_x
 *   mul1_x
 *   mul2_x
 *   mul3_x
 *   add2_y
 */
inline AdamApplyOneOutput AdamApplyOne(const EsTensorLike & input0, const EsTensorLike & input1, const EsTensorLike & input2, const EsTensorLike & input3, const EsTensorLike & input4, const EsTensorLike & mul0_x, const EsTensorLike & mul1_x, const EsTensorLike & mul2_x, const EsTensorLike & mul3_x, const EsTensorLike & add2_y) {
  auto *owner_graph_builder = ResolveBuilder(input0, input1, input2, input3, input4, mul0_x, mul1_x, mul2_x, mul3_x, add2_y);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsAdamApplyOne(input0.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input3.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input4.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mul0_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mul1_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mul2_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mul3_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), add2_y.ToTensorHolder(owner_graph_builder).GetCTensorHolder());
  return {out.output0, out.output1, out.output2};
}
}  // namespace es
}  // namespace ge
#endif
