/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AvgPool3DGrad_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AvgPool3DGrad_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_AvgPool3DGrad_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   orig_input_shape
 *   grads
 */
inline EsTensorHolder AvgPool3DGrad(const EsTensorLike & orig_input_shape, const EsTensorLike & grads, const std::vector<int64_t> & ksize, const std::vector<int64_t> & strides, const std::vector<int64_t> & pads, bool ceil_mode=false, bool count_include_pad=true, int64_t divisor_override=0, const char * data_format="NDHWC") {
  auto *owner_graph_builder = ResolveBuilder(orig_input_shape, grads);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsAvgPool3DGrad(orig_input_shape.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), grads.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), ksize.data(), static_cast<int64_t>(ksize.size()), strides.data(), static_cast<int64_t>(strides.size()), pads.data(), static_cast<int64_t>(pads.size()), ceil_mode, count_include_pad, divisor_override, data_format);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
