/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AvgPool3D_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AvgPool3D_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_AvgPool3D_c.h"
namespace ge {
namespace es {

inline EsTensorHolder AvgPool3D(const EsTensorHolder & x, const std::vector<int64_t> & ksize, const std::vector<int64_t> & strides, const std::vector<int64_t> & pads, bool ceil_mode=false, bool count_include_pad=true, int64_t divisor_override=0, const char * data_format="NDHWC") {
  auto out = EsAvgPool3D(x.GetCTensorHolder(), ksize.data(), static_cast<int64_t>(ksize.size()), strides.data(), static_cast<int64_t>(strides.size()), pads.data(), static_cast<int64_t>(pads.size()), ceil_mode, count_include_pad, divisor_override, data_format);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
