/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AddRmsNormDynamicQuant_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_AddRmsNormDynamicQuant_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_AddRmsNormDynamicQuant_c.h"
namespace ge {
namespace es {

struct AddRmsNormDynamicQuantOutput {
  EsTensorHolder y1;
  EsTensorHolder y2;
  EsTensorHolder x;
  EsTensorHolder scale1;
  EsTensorHolder scale2;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x1
 *   x2
 *   gamma
 *   smooth_scale1
 *   smooth_scale2
 *   beta
 */
inline AddRmsNormDynamicQuantOutput AddRmsNormDynamicQuant(const EsTensorLike & x1, const EsTensorLike & x2, const EsTensorLike & gamma, const EsTensorLike & smooth_scale1=nullptr, const EsTensorLike & smooth_scale2=nullptr, const EsTensorLike & beta=nullptr, float epsilon=0.000001, const std::vector<uint8_t> & output_mask={}, int64_t dst_type=2) {
  auto *owner_graph_builder = ResolveBuilder(x1, x2, gamma, smooth_scale1, smooth_scale2, beta);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsAddRmsNormDynamicQuant(x1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gamma.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), smooth_scale1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), smooth_scale2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), epsilon, static_cast<const bool *>(static_cast<const void *>(output_mask.data())), static_cast<int64_t>(output_mask.size()), dst_type);
  return {out.y1, out.y2, out.x, out.scale1, out.scale2};
}
}  // namespace es
}  // namespace ge
#endif
