/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ApplyFusedEmaAdam_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ApplyFusedEmaAdam_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_ApplyFusedEmaAdam_c.h"
namespace ge {
namespace es {

struct ApplyFusedEmaAdamOutput {
  EsTensorHolder ref_var;
  EsTensorHolder ref_m;
  EsTensorHolder ref_v;
  EsTensorHolder ref_s;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   grad
 *   var
 *   m
 *   v
 *   s
 *   step
 */
inline ApplyFusedEmaAdamOutput ApplyFusedEmaAdam(const EsTensorLike & grad, const EsTensorLike & var, const EsTensorLike & m, const EsTensorLike & v, const EsTensorLike & s, const EsTensorLike & step, float lr=0.001000, float ema_decay=0.999900, float beta1=0.900000, float beta2=0.999000, float eps=0.000000, int64_t mode=1, bool bias_correction=true, float weight_decay=0.000000) {
  auto *owner_graph_builder = ResolveBuilder(grad, var, m, v, s, step);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsApplyFusedEmaAdam(grad.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), var.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), m.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), v.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), s.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), step.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), lr, ema_decay, beta1, beta2, eps, mode, bias_correction, weight_decay);
  return {out.ref_var, out.ref_m, out.ref_v, out.ref_s};
}
}  // namespace es
}  // namespace ge
#endif
