/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ApplyAdamWV2_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ApplyAdamWV2_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_ApplyAdamWV2_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   var
 *   m
 *   v
 *   grad
 *   step
 *   max_grad_norm
 */
inline EsTensorHolder ApplyAdamWV2(const EsTensorLike & var, const EsTensorLike & m, const EsTensorLike & v, const EsTensorLike & grad, const EsTensorLike & step, const EsTensorLike & max_grad_norm=nullptr, float lr=0.100000, float beta1=0.100000, float beta2=0.100000, float weight_decay=0.100000, float eps=0.100000, bool amsgrad=false, bool maximize=false) {
  auto *owner_graph_builder = ResolveBuilder(var, m, v, grad, step, max_grad_norm);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsApplyAdamWV2(var.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), m.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), v.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), grad.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), step.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), max_grad_norm.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), lr, beta1, beta2, weight_decay, eps, amsgrad, maximize);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
