/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_BatchNormGradV3_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_BatchNormGradV3_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_BatchNormGradV3_c.h"
namespace ge {
namespace es {

struct BatchNormGradV3Output {
  EsTensorHolder dx;
  EsTensorHolder dweight;
  EsTensorHolder dbias;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   dy
 *   x
 *   weight
 *   running_mean
 *   running_var
 *   save_mean
 *   save_rstd
 */
inline BatchNormGradV3Output BatchNormGradV3(const EsTensorLike & dy, const EsTensorLike & x, const EsTensorLike & weight, const EsTensorLike & running_mean, const EsTensorLike & running_var, const EsTensorLike & save_mean, const EsTensorLike & save_rstd, bool is_training=true, float epsilon=0.000010) {
  auto *owner_graph_builder = ResolveBuilder(dy, x, weight, running_mean, running_var, save_mean, save_rstd);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsBatchNormGradV3(dy.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), weight.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), running_mean.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), running_var.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), save_mean.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), save_rstd.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), is_training, epsilon);
  return {out.dx, out.dweight, out.dbias};
}
}  // namespace es
}  // namespace ge
#endif
