/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_BatchNormGrad_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_BatchNormGrad_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_BatchNormGrad_c.h"
namespace ge {
namespace es {

struct BatchNormGradOutput {
  EsTensorHolder x_backprop;
  EsTensorHolder scale_backprop;
  EsTensorHolder offset_backprop;
  EsTensorHolder reserve_space_4;
  EsTensorHolder reserve_space_5;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   y_backprop
 *   x
 *   scale
 *   reserve_space_1
 *   reserve_space_2
 *   reserve_space_3
 */
inline BatchNormGradOutput BatchNormGrad(const EsTensorLike & y_backprop, const EsTensorLike & x, const EsTensorLike & scale, const EsTensorLike & reserve_space_1, const EsTensorLike & reserve_space_2, const EsTensorLike & reserve_space_3=nullptr, float epsilon=0.000100, const char * data_format="NHWC", bool is_training=true, const std::vector<uint8_t> & output_mask={true, false, false}) {
  auto *owner_graph_builder = ResolveBuilder(y_backprop, x, scale, reserve_space_1, reserve_space_2, reserve_space_3);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsBatchNormGrad(y_backprop.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), reserve_space_1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), reserve_space_2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), reserve_space_3.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), epsilon, data_format, is_training, static_cast<const bool *>(static_cast<const void *>(output_mask.data())), static_cast<int64_t>(output_mask.size()));
  return {out.x_backprop, out.scale_backprop, out.offset_backprop, out.reserve_space_4, out.reserve_space_5};
}
}  // namespace es
}  // namespace ge
#endif
