/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_BatchNormGrad_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_BatchNormGrad_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder *x_backprop;
  EsCTensorHolder *scale_backprop;
  EsCTensorHolder *offset_backprop;
  EsCTensorHolder *reserve_space_4;
  EsCTensorHolder *reserve_space_5;
} EsBatchNormGradOutput;
EsBatchNormGradOutput EsBatchNormGrad(EsCTensorHolder *y_backprop, EsCTensorHolder *x, EsCTensorHolder *scale, EsCTensorHolder *reserve_space_1, EsCTensorHolder *reserve_space_2, EsCTensorHolder *reserve_space_3, float epsilon, const char *data_format, bool is_training, const bool *output_mask, int64_t output_mask_num);
#ifdef __cplusplus
}
#endif
#endif
