/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_BatchNorm_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_BatchNorm_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_BatchNorm_c.h"
namespace ge {
namespace es {

struct BatchNormOutput {
  EsTensorHolder y;
  EsTensorHolder batch_mean;
  EsTensorHolder batch_variance;
  EsTensorHolder reserve_space_1;
  EsTensorHolder reserve_space_2;
  EsTensorHolder reserve_space_3;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   scale
 *   offset
 *   mean
 *   variance
 */
inline BatchNormOutput BatchNorm(const EsTensorLike & x, const EsTensorLike & scale, const EsTensorLike & offset, const EsTensorLike & mean=nullptr, const EsTensorLike & variance=nullptr, float epsilon=0.000100, const char * data_format="NHWC", bool is_training=true, float exponential_avg_factor=1.000000) {
  auto *owner_graph_builder = ResolveBuilder(x, scale, offset, mean, variance);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsBatchNorm(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mean.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), variance.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), epsilon, data_format, is_training, exponential_avg_factor);
  return {out.y, out.batch_mean, out.batch_variance, out.reserve_space_1, out.reserve_space_2, out.reserve_space_3};
}
}  // namespace es
}  // namespace ge
#endif
