/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_CTCLossV2Grad_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_CTCLossV2Grad_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_CTCLossV2Grad_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   grad_out
 *   log_probs
 *   targets
 *   input_lengths
 *   target_lengths
 *   neg_log_likelihood
 *   log_alpha
 */
inline EsTensorHolder CTCLossV2Grad(const EsTensorLike & grad_out, const EsTensorLike & log_probs, const EsTensorLike & targets, const EsTensorLike & input_lengths, const EsTensorLike & target_lengths, const EsTensorLike & neg_log_likelihood, const EsTensorLike & log_alpha, int64_t blank=0, const char * reduction="mean", bool zero_infinity=false) {
  auto *owner_graph_builder = ResolveBuilder(grad_out, log_probs, targets, input_lengths, target_lengths, neg_log_likelihood, log_alpha);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsCTCLossV2Grad(grad_out.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), log_probs.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), targets.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input_lengths.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), target_lengths.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), neg_log_likelihood.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), log_alpha.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), blank, reduction, zero_infinity);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
