/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_Conv3DBackpropFilterV2_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_Conv3DBackpropFilterV2_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_Conv3DBackpropFilterV2_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   filter_size
 *   out_backprop
 */
inline EsTensorHolder Conv3DBackpropFilterV2(const EsTensorLike & x, const EsTensorLike & filter_size, const EsTensorLike & out_backprop, const std::vector<int64_t> & strides, const std::vector<int64_t> & pads, const std::vector<int64_t> & dilations={1, 1, 1, 1, 1}, int64_t groups=1, const char * data_format="NDHWC", bool enable_hf32=false) {
  auto *owner_graph_builder = ResolveBuilder(x, filter_size, out_backprop);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsConv3DBackpropFilterV2(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), filter_size.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), out_backprop.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), strides.data(), static_cast<int64_t>(strides.size()), pads.data(), static_cast<int64_t>(pads.size()), dilations.data(), static_cast<int64_t>(dilations.size()), groups, data_format, enable_hf32);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
