/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DynamicRNNV2_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DynamicRNNV2_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_DynamicRNNV2_c.h"
namespace ge {
namespace es {

struct DynamicRNNV2Output {
  EsTensorHolder y;
  EsTensorHolder output_h;
  EsTensorHolder output_c;
  EsTensorHolder i;
  EsTensorHolder j;
  EsTensorHolder f;
  EsTensorHolder o;
  EsTensorHolder tanhc;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   weight_input
 *   weight_hidden
 *   b
 *   seq_length
 *   init_h
 *   init_c
 *   wci
 *   wcf
 *   wco
 *   mask
 */
inline DynamicRNNV2Output DynamicRNNV2(const EsTensorLike & x, const EsTensorLike & weight_input, const EsTensorLike & weight_hidden, const EsTensorLike & b=nullptr, const EsTensorLike & seq_length=nullptr, const EsTensorLike & init_h=nullptr, const EsTensorLike & init_c=nullptr, const EsTensorLike & wci=nullptr, const EsTensorLike & wcf=nullptr, const EsTensorLike & wco=nullptr, const EsTensorLike & mask=nullptr, const char * cell_type="LSTM", const char * direction="UNIDIRECTIONAL", int64_t cell_depth=1, bool use_peephole=false, float keep_prob=1.000000, float cell_clip=-1.000000, int64_t num_proj=0, bool time_major=true, const char * activation="tanh", const char * recurrent_activation="sigmoid", float forget_bias=0.000000, const char * gate_order="ijfo", bool stateful=false, const char * merge_mode="concat", bool is_training=true) {
  auto *owner_graph_builder = ResolveBuilder(x, weight_input, weight_hidden, b, seq_length, init_h, init_c, wci, wcf, wco, mask);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsDynamicRNNV2(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), weight_input.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), weight_hidden.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), b.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), seq_length.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), init_h.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), init_c.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), wci.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), wcf.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), wco.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mask.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), cell_type, direction, cell_depth, use_peephole, keep_prob, cell_clip, num_proj, time_major, activation, recurrent_activation, forget_bias, gate_order, stateful, merge_mode, is_training);
  return {out.y, out.output_h, out.output_c, out.i, out.j, out.f, out.o, out.tanhc};
}
}  // namespace es
}  // namespace ge
#endif
