/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DynamicBlockMxQuant_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DynamicBlockMxQuant_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_DynamicBlockMxQuant_c.h"
namespace ge {
namespace es {

struct DynamicBlockMxQuantOutput {
  EsTensorHolder y;
  EsTensorHolder scale1;
  EsTensorHolder scale2;
};
inline DynamicBlockMxQuantOutput DynamicBlockMxQuant(const EsTensorHolder & x, const char * round_mode="rint", int64_t dst_type=40, int64_t scale_alg=0, float dst_type_max=0.000000) {
  auto out = EsDynamicBlockMxQuant(x.GetCTensorHolder(), round_mode, dst_type, scale_alg, dst_type_max);
  return {out.y, out.scale1, out.scale2};
}
}  // namespace es
}  // namespace ge
#endif
