/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DeformableOffsetsGrad_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DeformableOffsetsGrad_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_DeformableOffsetsGrad_c.h"
namespace ge {
namespace es {

struct DeformableOffsetsGradOutput {
  EsTensorHolder grad_x;
  EsTensorHolder grad_offsets;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   grad
 *   x
 *   offsets
 */
inline DeformableOffsetsGradOutput DeformableOffsetsGrad(const EsTensorLike & grad, const EsTensorLike & x, const EsTensorLike & offsets, const std::vector<int64_t> & strides, const std::vector<int64_t> & pads, const std::vector<int64_t> & ksize, const std::vector<int64_t> & dilations={1, 1, 1, 1}, const char * data_format="NCHW", int64_t deformable_groups=1, bool modulated=true) {
  auto *owner_graph_builder = ResolveBuilder(grad, x, offsets);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsDeformableOffsetsGrad(grad.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), offsets.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), strides.data(), static_cast<int64_t>(strides.size()), pads.data(), static_cast<int64_t>(pads.size()), ksize.data(), static_cast<int64_t>(ksize.size()), dilations.data(), static_cast<int64_t>(dilations.size()), data_format, deformable_groups, modulated);
  return {out.grad_x, out.grad_offsets};
}
}  // namespace es
}  // namespace ge
#endif
