/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DynamicQuantUpdateScatterV2_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DynamicQuantUpdateScatterV2_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_DynamicQuantUpdateScatterV2_c.h"
namespace ge {
namespace es {

struct DynamicQuantUpdateScatterV2Output {
  EsTensorHolder ref_var;
  EsTensorHolder ref_var_scale;
  EsTensorHolder ref_var_offset;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   indices
 *   var
 *   var_scale
 *   var_offset
 */
inline DynamicQuantUpdateScatterV2Output DynamicQuantUpdateScatterV2(const EsTensorLike & x, const EsTensorLike & indices, const EsTensorLike & var, const EsTensorLike & var_scale, const EsTensorLike & var_offset) {
  auto *owner_graph_builder = ResolveBuilder(x, indices, var, var_scale, var_offset);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsDynamicQuantUpdateScatterV2(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), indices.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), var.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), var_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), var_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder());
  return {out.ref_var, out.ref_var_scale, out.ref_var_offset};
}
}  // namespace es
}  // namespace ge
#endif
