/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DeepNorm_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DeepNorm_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_DeepNorm_c.h"
namespace ge {
namespace es {

struct DeepNormOutput {
  EsTensorHolder mean;
  EsTensorHolder rstd;
  EsTensorHolder y;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   gx
 *   beta
 *   gamma
 */
inline DeepNormOutput DeepNorm(const EsTensorLike & x, const EsTensorLike & gx, const EsTensorLike & beta, const EsTensorLike & gamma, float alpha=0.300000, float epsilon=0.000001) {
  auto *owner_graph_builder = ResolveBuilder(x, gx, beta, gamma);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsDeepNorm(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gx.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gamma.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), alpha, epsilon);
  return {out.mean, out.rstd, out.y};
}
}  // namespace es
}  // namespace ge
#endif
