/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DequantSwigluQuant_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DequantSwigluQuant_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_DequantSwigluQuant_c.h"
namespace ge {
namespace es {

struct DequantSwigluQuantOutput {
  EsTensorHolder y;
  EsTensorHolder scale;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   weight_scale
 *   activation_scale
 *   bias
 *   quant_scale
 *   quant_offset
 *   group_index
 */
inline DequantSwigluQuantOutput DequantSwigluQuant(const EsTensorLike & x, const EsTensorLike & weight_scale=nullptr, const EsTensorLike & activation_scale=nullptr, const EsTensorLike & bias=nullptr, const EsTensorLike & quant_scale=nullptr, const EsTensorLike & quant_offset=nullptr, const EsTensorLike & group_index=nullptr, bool activate_left=false, const char * quant_mode="static", int64_t dst_type=2, const char * round_mode="rint", int64_t activate_dim=-1, int64_t swiglu_mode=0, float clamp_limit=7.000000, float glu_alpha=1.702000, float glu_bias=1.000000) {
  auto *owner_graph_builder = ResolveBuilder(x, weight_scale, activation_scale, bias, quant_scale, quant_offset, group_index);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsDequantSwigluQuant(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), weight_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), activation_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bias.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), group_index.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), activate_left, quant_mode, dst_type, round_mode, activate_dim, swiglu_mode, clamp_limit, glu_alpha, glu_bias);
  return {out.y, out.scale};
}
}  // namespace es
}  // namespace ge
#endif
