/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DynamicRNNV2_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_DynamicRNNV2_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder *y;
  EsCTensorHolder *output_h;
  EsCTensorHolder *output_c;
  EsCTensorHolder *i;
  EsCTensorHolder *j;
  EsCTensorHolder *f;
  EsCTensorHolder *o;
  EsCTensorHolder *tanhc;
} EsDynamicRNNV2Output;
EsDynamicRNNV2Output EsDynamicRNNV2(EsCTensorHolder *x, EsCTensorHolder *weight_input, EsCTensorHolder *weight_hidden, EsCTensorHolder *b, EsCTensorHolder *seq_length, EsCTensorHolder *init_h, EsCTensorHolder *init_c, EsCTensorHolder *wci, EsCTensorHolder *wcf, EsCTensorHolder *wco, EsCTensorHolder *mask, const char *cell_type, const char *direction, int64_t cell_depth, bool use_peephole, float keep_prob, float cell_clip, int64_t num_proj, bool time_major, const char *activation, const char *recurrent_activation, float forget_bias, const char *gate_order, bool stateful, const char *merge_mode, bool is_training);
#ifdef __cplusplus
}
#endif
#endif
