/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_EmbeddingHashTableApplyAdamW_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_EmbeddingHashTableApplyAdamW_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_EmbeddingHashTableApplyAdamW_c.h"
namespace ge {
namespace es {

struct EmbeddingHashTableApplyAdamWOutput {
  EsTensorHolder ref_m;
  EsTensorHolder ref_v;
  EsTensorHolder ref_beta1_power;
  EsTensorHolder ref_beta2_power;
  EsTensorHolder ref_max_grad_norm;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   table_handle
 *   keys
 *   m
 *   v
 *   beta1_power
 *   beta2_power
 *   lr
 *   weight_decay
 *   beta1
 *   beta2
 *   epsilon
 *   grad
 *   max_grad_norm
 */
inline EmbeddingHashTableApplyAdamWOutput EmbeddingHashTableApplyAdamW(const EsTensorLike & table_handle, const EsTensorLike & keys, const EsTensorLike & m, const EsTensorLike & v, const EsTensorLike & beta1_power, const EsTensorLike & beta2_power, const EsTensorLike & lr, const EsTensorLike & weight_decay, const EsTensorLike & beta1, const EsTensorLike & beta2, const EsTensorLike & epsilon, const EsTensorLike & grad, const EsTensorLike & max_grad_norm, int64_t embedding_dim, int64_t bucket_size, bool amsgrad=false, bool maximize=false) {
  auto *owner_graph_builder = ResolveBuilder(table_handle, keys, m, v, beta1_power, beta2_power, lr, weight_decay, beta1, beta2, epsilon, grad, max_grad_norm);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsEmbeddingHashTableApplyAdamW(table_handle.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), keys.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), m.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), v.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta1_power.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta2_power.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), lr.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), weight_decay.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), epsilon.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), grad.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), max_grad_norm.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), embedding_dim, bucket_size, amsgrad, maximize);
  return {out.ref_m, out.ref_v, out.ref_beta1_power, out.ref_beta2_power, out.ref_max_grad_norm};
}
}  // namespace es
}  // namespace ge
#endif
