/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ExtendConv2D_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ExtendConv2D_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_ExtendConv2D_c.h"
namespace ge {
namespace es {

struct ExtendConv2DOutput {
  EsTensorHolder y0;
  EsTensorHolder y1;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   filter
 *   bias
 *   offset_w
 *   scale0
 *   relu_weight0
 *   clip_value0
 *   scale1
 *   relu_weight1
 *   clip_value1
 */
inline ExtendConv2DOutput ExtendConv2D(const EsTensorLike & x, const EsTensorLike & filter, const EsTensorLike & bias, const EsTensorLike & offset_w, const EsTensorLike & scale0, const EsTensorLike & relu_weight0, const EsTensorLike & clip_value0, const EsTensorLike & scale1, const EsTensorLike & relu_weight1, const EsTensorLike & clip_value1, const std::vector<int64_t> & strides, const std::vector<int64_t> & pads={0, 0, 0, 0}, const std::vector<int64_t> & dilations={1, 1, 1, 1}, int64_t groups=1, const char * data_format="NCHW", int64_t offset_x=0, const char * round_mode="rint", const char * pad_mode="SPECIFIC", bool enable_hf32=false, bool enable_relu0=false, bool enable_relu1=false, bool dual_output=false, int64_t dtype0=-1, int64_t dtype1=-1) {
  auto *owner_graph_builder = ResolveBuilder(x, filter, bias, offset_w, scale0, relu_weight0, clip_value0, scale1, relu_weight1, clip_value1);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsExtendConv2D(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), filter.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bias.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), offset_w.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scale0.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), relu_weight0.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), clip_value0.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scale1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), relu_weight1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), clip_value1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), strides.data(), static_cast<int64_t>(strides.size()), pads.data(), static_cast<int64_t>(pads.size()), dilations.data(), static_cast<int64_t>(dilations.size()), groups, data_format, offset_x, round_mode, pad_mode, enable_hf32, enable_relu0, enable_relu1, dual_output, dtype0, dtype1);
  return {out.y0, out.y1};
}
}  // namespace es
}  // namespace ge
#endif
