/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_EmbeddingHashTableApplyAdamW_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_EmbeddingHashTableApplyAdamW_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder *ref_m;
  EsCTensorHolder *ref_v;
  EsCTensorHolder *ref_beta1_power;
  EsCTensorHolder *ref_beta2_power;
  EsCTensorHolder *ref_max_grad_norm;
} EsEmbeddingHashTableApplyAdamWOutput;
EsEmbeddingHashTableApplyAdamWOutput EsEmbeddingHashTableApplyAdamW(EsCTensorHolder *table_handle, EsCTensorHolder *keys, EsCTensorHolder *m, EsCTensorHolder *v, EsCTensorHolder *beta1_power, EsCTensorHolder *beta2_power, EsCTensorHolder *lr, EsCTensorHolder *weight_decay, EsCTensorHolder *beta1, EsCTensorHolder *beta2, EsCTensorHolder *epsilon, EsCTensorHolder *grad, EsCTensorHolder *max_grad_norm, int64_t embedding_dim, int64_t bucket_size, bool amsgrad, bool maximize);
#ifdef __cplusplus
}
#endif
#endif
