/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_EmbeddingHashTableExport_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_EmbeddingHashTableExport_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder **keys;
  int64_t keys_num;
  EsCTensorHolder **counters;
  int64_t counters_num;
  EsCTensorHolder **filter_flags;
  int64_t filter_flags_num;
  EsCTensorHolder **values;
  int64_t values_num;
} EsEmbeddingHashTableExportOutput;
/**
 * @note user needs to provide following inputs for dynamic output numbers:
 *   keys_num: dynamic output number of keys
 *   counters_num: dynamic output number of counters
 *   filter_flags_num: dynamic output number of filter_flags
 *   values_num: dynamic output number of values
 */
EsEmbeddingHashTableExportOutput EsEmbeddingHashTableExport(EsCTensorHolder *table_handles, EsCTensorHolder *table_sizes, EsCTensorHolder *embedding_dims, EsCTensorHolder *bucket_sizes, int64_t keys_num, int64_t counters_num, int64_t filter_flags_num, int64_t values_num, const char *export_mode, bool filtered_export_flag);
#ifdef __cplusplus
}
#endif
#endif
