/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_EmbeddingBag_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_EmbeddingBag_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_EmbeddingBag_c.h"
namespace ge {
namespace es {

struct EmbeddingBagOutput {
  EsTensorHolder y;
  EsTensorHolder offset2bag;
  EsTensorHolder bag_size;
  EsTensorHolder max_indices;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   weight
 *   indices
 *   offsets
 *   per_sample_weights
 */
inline EmbeddingBagOutput EmbeddingBag(const EsTensorLike & weight, const EsTensorLike & indices, const EsTensorLike & offsets=nullptr, const EsTensorLike & per_sample_weights=nullptr, const char * mode="mean", bool scale_grad_by_freq=false, bool sparse=false, bool include_last_offset=false, int64_t padding_idx=-1) {
  auto *owner_graph_builder = ResolveBuilder(weight, indices, offsets, per_sample_weights);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsEmbeddingBag(weight.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), indices.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), offsets.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), per_sample_weights.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mode, scale_grad_by_freq, sparse, include_last_offset, padding_idx);
  return {out.y, out.offset2bag, out.bag_size, out.max_indices};
}
}  // namespace es
}  // namespace ge
#endif
