/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ExtendConv2D_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ExtendConv2D_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder *y0;
  EsCTensorHolder *y1;
} EsExtendConv2DOutput;
EsExtendConv2DOutput EsExtendConv2D(EsCTensorHolder *x, EsCTensorHolder *filter, EsCTensorHolder *bias, EsCTensorHolder *offset_w, EsCTensorHolder *scale0, EsCTensorHolder *relu_weight0, EsCTensorHolder *clip_value0, EsCTensorHolder *scale1, EsCTensorHolder *relu_weight1, EsCTensorHolder *clip_value1, const int64_t *strides, int64_t strides_num, const int64_t *pads, int64_t pads_num, const int64_t *dilations, int64_t dilations_num, int64_t groups, const char *data_format, int64_t offset_x, const char *round_mode, const char *pad_mode, bool enable_hf32, bool enable_relu0, bool enable_relu1, bool dual_output, int64_t dtype0, int64_t dtype1);
#ifdef __cplusplus
}
#endif
#endif
