/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_EmbeddingHashTableLookupOrInsert_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_EmbeddingHashTableLookupOrInsert_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_EmbeddingHashTableLookupOrInsert_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   table_handle
 *   keys
 */
inline EsTensorHolder EmbeddingHashTableLookupOrInsert(const EsTensorLike & table_handle, const EsTensorLike & keys, int64_t bucket_size, int64_t embedding_dim, const char * filter_mode="no_filter", int64_t filter_freq=0, bool default_key_or_value=false, int64_t default_key=0, float default_value=0.000000, bool filter_key_flag=false, int64_t filter_key=-1) {
  auto *owner_graph_builder = ResolveBuilder(table_handle, keys);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsEmbeddingHashTableLookupOrInsert(table_handle.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), keys.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bucket_size, embedding_dim, filter_mode, filter_freq, default_key_or_value, default_key, default_value, filter_key_flag, filter_key);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
