/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_EmbeddingHashTableImport_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_EmbeddingHashTableImport_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_EmbeddingHashTableImport_c.h"
namespace ge {
namespace es {

inline EsTensorHolder EmbeddingHashTableImport(const EsTensorLike & table_handles, const EsTensorLike & embedding_dims, const EsTensorLike & bucket_sizes, const std::vector<EsTensorHolder> & keys, const std::vector<EsTensorHolder> & counters, const std::vector<EsTensorHolder> & filter_flags, const std::vector<EsTensorHolder> & values) {
  auto *owner_graph_builder = ResolveBuilder(table_handles, embedding_dims, bucket_sizes, keys, counters, filter_flags, values);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto esb_keys = TensorsToEsCTensorHolders(keys);
  auto esb_counters = TensorsToEsCTensorHolders(counters);
  auto esb_filter_flags = TensorsToEsCTensorHolders(filter_flags);
  auto esb_values = TensorsToEsCTensorHolders(values);
  auto out = EsEmbeddingHashTableImport(table_handles.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), embedding_dims.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bucket_sizes.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), esb_keys.data(), static_cast<int64_t>(esb_keys.size()), esb_counters.data(), static_cast<int64_t>(esb_counters.size()), esb_filter_flags.data(), static_cast<int64_t>(esb_filter_flags.size()), esb_values.data(), static_cast<int64_t>(esb_values.size()));
  return out;
}
}  // namespace es
}  // namespace ge
#endif
