/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_GroupedDynamicBlockQuant_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_GroupedDynamicBlockQuant_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_GroupedDynamicBlockQuant_c.h"
namespace ge {
namespace es {

struct GroupedDynamicBlockQuantOutput {
  EsTensorHolder y;
  EsTensorHolder scale;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   group_list
 */
inline GroupedDynamicBlockQuantOutput GroupedDynamicBlockQuant(const EsTensorLike & x, const EsTensorLike & group_list, float min_scale=0.000000, const char * round_mode="rint", int64_t dst_type=35, int64_t row_block_size=1, int64_t col_block_size=128, int64_t group_list_type=0) {
  auto *owner_graph_builder = ResolveBuilder(x, group_list);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsGroupedDynamicBlockQuant(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), group_list.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), min_scale, round_mode, dst_type, row_block_size, col_block_size, group_list_type);
  return {out.y, out.scale};
}
}  // namespace es
}  // namespace ge
#endif
