/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_GeluQuant_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_GeluQuant_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_GeluQuant_c.h"
namespace ge {
namespace es {

struct GeluQuantOutput {
  EsTensorHolder y;
  EsTensorHolder out_scale;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   input_scale
 *   input_offset
 */
inline GeluQuantOutput GeluQuant(const EsTensorLike & x, const EsTensorLike & input_scale=nullptr, const EsTensorLike & input_offset=nullptr, const char * approximate="none", const char * quant_mode="dynamic", int64_t dst_type=2, const char * round_mode="rint") {
  auto *owner_graph_builder = ResolveBuilder(x, input_scale, input_offset);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsGeluQuant(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), approximate, quant_mode, dst_type, round_mode);
  return {out.y, out.out_scale};
}
}  // namespace es
}  // namespace ge
#endif
