/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_GroupNormSwishGrad_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_GroupNormSwishGrad_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_GroupNormSwishGrad_c.h"
namespace ge {
namespace es {

struct GroupNormSwishGradOutput {
  EsTensorHolder dx;
  EsTensorHolder dgamma;
  EsTensorHolder dbeta;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   dy
 *   mean
 *   rstd
 *   x
 *   gamma
 *   beta
 */
inline GroupNormSwishGradOutput GroupNormSwishGrad(const EsTensorLike & dy, const EsTensorLike & mean, const EsTensorLike & rstd, const EsTensorLike & x, const EsTensorLike & gamma, const EsTensorLike & beta, int64_t num_groups, const char * data_format="NCHW", float swish_scale=1.000000, bool dgamma_is_require=true, bool dbeta_is_require=true) {
  auto *owner_graph_builder = ResolveBuilder(dy, mean, rstd, x, gamma, beta);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsGroupNormSwishGrad(dy.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mean.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), rstd.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gamma.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), num_groups, data_format, swish_scale, dgamma_is_require, dbeta_is_require);
  return {out.dx, out.dgamma, out.dbeta};
}
}  // namespace es
}  // namespace ge
#endif
