/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_GroupNormV2_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_GroupNormV2_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_GroupNormV2_c.h"
namespace ge {
namespace es {

struct GroupNormV2Output {
  EsTensorHolder y;
  EsTensorHolder mean;
  EsTensorHolder rstd;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   gamma
 *   beta
 */
inline GroupNormV2Output GroupNormV2(const EsTensorLike & x, const EsTensorLike & gamma, const EsTensorLike & beta, int64_t num_groups, const char * data_format="NHWC", float eps=0.000010, bool is_training=true) {
  auto *owner_graph_builder = ResolveBuilder(x, gamma, beta);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsGroupNormV2(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gamma.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), num_groups, data_format, eps, is_training);
  return {out.y, out.mean, out.rstd};
}
}  // namespace es
}  // namespace ge
#endif
