/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_IFMR_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_IFMR_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_IFMR_c.h"
namespace ge {
namespace es {

struct IFMROutput {
  EsTensorHolder scale;
  EsTensorHolder offset;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   data
 *   data_min
 *   data_max
 *   cumsum
 */
inline IFMROutput IFMR(const EsTensorLike & data, const EsTensorLike & data_min, const EsTensorLike & data_max, const EsTensorLike & cumsum, float min_percentile, float max_percentile, const std::vector<float> & search_range, float search_step, bool with_offset, int64_t quant_bits=8) {
  auto *owner_graph_builder = ResolveBuilder(data, data_min, data_max, cumsum);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsIFMR(data.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), data_min.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), data_max.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), cumsum.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), min_percentile, max_percentile, search_range.data(), static_cast<int64_t>(search_range.size()), search_step, with_offset, quant_bits);
  return {out.scale, out.offset};
}
}  // namespace es
}  // namespace ge
#endif
