/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_IndexPutV2_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_IndexPutV2_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_IndexPutV2_c.h"
namespace ge {
namespace es {

inline EsTensorHolder IndexPutV2(const EsTensorLike & x, const EsTensorLike & value, const EsTensorLike & indexed_sizes, const EsTensorLike & indexed_strides, const std::vector<EsTensorHolder> & indices, bool accumulate=false) {
  auto *owner_graph_builder = ResolveBuilder(x, value, indexed_sizes, indexed_strides, indices);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto esb_indices = TensorsToEsCTensorHolders(indices);
  auto out = EsIndexPutV2(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), value.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), indexed_sizes.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), indexed_strides.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), esb_indices.data(), static_cast<int64_t>(esb_indices.size()), accumulate);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
