/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_LambNextRight_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_LambNextRight_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_LambNextRight_c.h"
namespace ge {
namespace es {

struct LambNextRightOutput {
  EsTensorHolder y1;
  EsTensorHolder y2;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   input_square
 *   input_mul2
 *   mul2_x
 *   mul3_x
 *   truediv1_recip
 *   add2_y
 */
inline LambNextRightOutput LambNextRight(const EsTensorLike & input_square, const EsTensorLike & input_mul2, const EsTensorLike & mul2_x, const EsTensorLike & mul3_x, const EsTensorLike & truediv1_recip, const EsTensorLike & add2_y) {
  auto *owner_graph_builder = ResolveBuilder(input_square, input_mul2, mul2_x, mul3_x, truediv1_recip, add2_y);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsLambNextRight(input_square.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input_mul2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mul2_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mul3_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), truediv1_recip.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), add2_y.ToTensorHolder(owner_graph_builder).GetCTensorHolder());
  return {out.y1, out.y2};
}
}  // namespace es
}  // namespace ge
#endif
