/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_LambApplyOptimizerAssign_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_LambApplyOptimizerAssign_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_LambApplyOptimizerAssign_c.h"
namespace ge {
namespace es {

struct LambApplyOptimizerAssignOutput {
  EsTensorHolder output0;
  EsTensorHolder ref_inputv;
  EsTensorHolder ref_inputm;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   grad
 *   inputv
 *   inputm
 *   input3
 *   mul0_x
 *   mul1_x
 *   mul2_x
 *   mul3_x
 *   add2_y
 *   steps
 *   do_use_weight
 *   weight_decay_rate
 */
inline LambApplyOptimizerAssignOutput LambApplyOptimizerAssign(const EsTensorLike & grad, const EsTensorLike & inputv, const EsTensorLike & inputm, const EsTensorLike & input3, const EsTensorLike & mul0_x, const EsTensorLike & mul1_x, const EsTensorLike & mul2_x, const EsTensorLike & mul3_x, const EsTensorLike & add2_y, const EsTensorLike & steps, const EsTensorLike & do_use_weight, const EsTensorLike & weight_decay_rate) {
  auto *owner_graph_builder = ResolveBuilder(grad, inputv, inputm, input3, mul0_x, mul1_x, mul2_x, mul3_x, add2_y, steps, do_use_weight, weight_decay_rate);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsLambApplyOptimizerAssign(grad.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), inputv.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), inputm.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input3.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mul0_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mul1_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mul2_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mul3_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), add2_y.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), steps.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), do_use_weight.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), weight_decay_rate.ToTensorHolder(owner_graph_builder).GetCTensorHolder());
  return {out.output0, out.ref_inputv, out.ref_inputm};
}
}  // namespace es
}  // namespace ge
#endif
