/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_LambUpdateWithLr_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_LambUpdateWithLr_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_LambUpdateWithLr_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   input_greater1
 *   input_greater_realdiv
 *   input_realdiv
 *   input_mul0
 *   input_mul1
 *   input_sub
 *   greater_y
 *   select_e
 *   minimum_y
 */
inline EsTensorHolder LambUpdateWithLr(const EsTensorLike & input_greater1, const EsTensorLike & input_greater_realdiv, const EsTensorLike & input_realdiv, const EsTensorLike & input_mul0, const EsTensorLike & input_mul1, const EsTensorLike & input_sub, const EsTensorLike & greater_y, const EsTensorLike & select_e, const EsTensorLike & minimum_y) {
  auto *owner_graph_builder = ResolveBuilder(input_greater1, input_greater_realdiv, input_realdiv, input_mul0, input_mul1, input_sub, greater_y, select_e, minimum_y);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsLambUpdateWithLr(input_greater1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input_greater_realdiv.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input_realdiv.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input_mul0.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input_mul1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input_sub.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), greater_y.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), select_e.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), minimum_y.ToTensorHolder(owner_graph_builder).GetCTensorHolder());
  return out;
}
}  // namespace es
}  // namespace ge
#endif
