/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_LayerNormGradV3_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_LayerNormGradV3_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_LayerNormGradV3_c.h"
namespace ge {
namespace es {

struct LayerNormGradV3Output {
  EsTensorHolder pd_x;
  EsTensorHolder pd_gamma;
  EsTensorHolder pd_beta;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   dy
 *   x
 *   rstd
 *   mean
 *   gamma
 */
inline LayerNormGradV3Output LayerNormGradV3(const EsTensorLike & dy, const EsTensorLike & x, const EsTensorLike & rstd, const EsTensorLike & mean, const EsTensorLike & gamma, const std::vector<uint8_t> & output_mask={true, true, true}) {
  auto *owner_graph_builder = ResolveBuilder(dy, x, rstd, mean, gamma);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsLayerNormGradV3(dy.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), rstd.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mean.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gamma.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), static_cast<const bool *>(static_cast<const void *>(output_mask.data())), static_cast<int64_t>(output_mask.size()));
  return {out.pd_x, out.pd_gamma, out.pd_beta};
}
}  // namespace es
}  // namespace ge
#endif
