/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MaxPool3DWithArgmaxV2_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MaxPool3DWithArgmaxV2_H_
#include "esb_funcs.h"
#include <stdint.h>
#include "graph/types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  EsCTensorHolder *y;
  EsCTensorHolder *argmax;
} EsMaxPool3DWithArgmaxV2Output;
EsMaxPool3DWithArgmaxV2Output EsMaxPool3DWithArgmaxV2(EsCTensorHolder *x, const int64_t *ksize, int64_t ksize_num, const int64_t *strides, int64_t strides_num, const int64_t *pads, int64_t pads_num, const int64_t *dilation, int64_t dilation_num, bool ceil_mode, const char *data_format, int64_t dtype);
#ifdef __cplusplus
}
#endif
#endif
