/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MultiScaleDeformableAttentionGrad_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MultiScaleDeformableAttentionGrad_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_MultiScaleDeformableAttentionGrad_c.h"
namespace ge {
namespace es {

struct MultiScaleDeformableAttentionGradOutput {
  EsTensorHolder grad_value;
  EsTensorHolder grad_sampling_locations;
  EsTensorHolder grad_attention_weights;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   value
 *   value_spatial_shapes
 *   value_level_start_index
 *   sampling_locations
 *   attention_weights
 *   grad_output
 */
inline MultiScaleDeformableAttentionGradOutput MultiScaleDeformableAttentionGrad(const EsTensorLike & value, const EsTensorLike & value_spatial_shapes, const EsTensorLike & value_level_start_index, const EsTensorLike & sampling_locations, const EsTensorLike & attention_weights, const EsTensorLike & grad_output) {
  auto *owner_graph_builder = ResolveBuilder(value, value_spatial_shapes, value_level_start_index, sampling_locations, attention_weights, grad_output);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsMultiScaleDeformableAttentionGrad(value.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), value_spatial_shapes.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), value_level_start_index.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), sampling_locations.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), attention_weights.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), grad_output.ToTensorHolder(owner_graph_builder).GetCTensorHolder());
  return {out.grad_value, out.grad_sampling_locations, out.grad_attention_weights};
}
}  // namespace es
}  // namespace ge
#endif
