/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MultiAddRmsNormDynamicQuant_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_MultiAddRmsNormDynamicQuant_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_MultiAddRmsNormDynamicQuant_c.h"
namespace ge {
namespace es {

struct MultiAddRmsNormDynamicQuantOutput {
  EsTensorHolder y1;
  EsTensorHolder y2;
  EsTensorHolder x;
  EsTensorHolder y;
  EsTensorHolder scale1;
  EsTensorHolder scale2;
};
inline MultiAddRmsNormDynamicQuantOutput MultiAddRmsNormDynamicQuant(const std::vector<EsTensorHolder> & x1, const EsTensorLike & x2, const EsTensorLike & gamma, const EsTensorLike & smooth_scale1=nullptr, const EsTensorLike & smooth_scale2=nullptr, float epsilon=0.000001) {
  auto *owner_graph_builder = ResolveBuilder(x1, x2, gamma, smooth_scale1, smooth_scale2);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto esb_x1 = TensorsToEsCTensorHolders(x1);
  auto out = EsMultiAddRmsNormDynamicQuant(esb_x1.data(), static_cast<int64_t>(esb_x1.size()), x2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gamma.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), smooth_scale1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), smooth_scale2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), epsilon);
  return {out.y1, out.y2, out.x, out.y, out.scale1, out.scale2};
}
}  // namespace es
}  // namespace ge
#endif
