/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_QuantUpdateScatter_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_QuantUpdateScatter_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_QuantUpdateScatter_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   var
 *   indices
 *   updates
 *   quant_scales
 *   quant_zero_points
 */
inline EsTensorHolder QuantUpdateScatter(const EsTensorLike & var, const EsTensorLike & indices, const EsTensorLike & updates, const EsTensorLike & quant_scales, const EsTensorLike & quant_zero_points, const char * reduce, int64_t axis=-2, int64_t quant_axis=-1, bool reciprocal_scale=false, const char * round_mode="rint") {
  auto *owner_graph_builder = ResolveBuilder(var, indices, updates, quant_scales, quant_zero_points);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsQuantUpdateScatter(var.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), indices.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), updates.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_scales.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_zero_points.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), reduce, axis, quant_axis, reciprocal_scale, round_mode);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
