/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_RmsNormGradQuant_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_RmsNormGradQuant_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_RmsNormGradQuant_c.h"
namespace ge {
namespace es {

struct RmsNormGradQuantOutput {
  EsTensorHolder dx;
  EsTensorHolder dgamma;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   dy
 *   x
 *   rstd
 *   gamma
 *   scales_x
 *   offset_x
 */
inline RmsNormGradQuantOutput RmsNormGradQuant(const EsTensorLike & dy, const EsTensorLike & x, const EsTensorLike & rstd, const EsTensorLike & gamma, const EsTensorLike & scales_x, const EsTensorLike & offset_x=nullptr, const char * quant_mode="static", bool div_mode=true, int64_t dst_type=2) {
  auto *owner_graph_builder = ResolveBuilder(dy, x, rstd, gamma, scales_x, offset_x);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsRmsNormGradQuant(dy.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), rstd.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gamma.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scales_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), offset_x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_mode, div_mode, dst_type);
  return {out.dx, out.dgamma};
}
}  // namespace es
}  // namespace ge
#endif
