/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_RotateQuant_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_RotateQuant_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_RotateQuant_c.h"
namespace ge {
namespace es {

struct RotateQuantOutput {
  EsTensorHolder y;
  EsTensorHolder scale;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   rot
 *   alpha
 */
inline RotateQuantOutput RotateQuant(const EsTensorLike & x, const EsTensorLike & rot, const EsTensorLike & alpha=nullptr, int64_t y_dtype=2, int64_t axis=-1, const char * round_mode="rint", int64_t scale_alg=0, float dst_type_max=0.000000, bool trans=false) {
  auto *owner_graph_builder = ResolveBuilder(x, rot, alpha);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsRotateQuant(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), rot.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), alpha.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), y_dtype, axis, round_mode, scale_alg, dst_type_max, trans);
  return {out.y, out.scale};
}
}  // namespace es
}  // namespace ge
#endif
