/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_RmsNormQuantV2_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_RmsNormQuantV2_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_RmsNormQuantV2_c.h"
namespace ge {
namespace es {

struct RmsNormQuantV2Output {
  EsTensorHolder y1;
  EsTensorHolder y2;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   gamma
 *   scales1
 *   scales2
 *   zero_points1
 *   zero_points2
 *   beta
 */
inline RmsNormQuantV2Output RmsNormQuantV2(const EsTensorLike & x, const EsTensorLike & gamma, const EsTensorLike & scales1, const EsTensorLike & scales2=nullptr, const EsTensorLike & zero_points1=nullptr, const EsTensorLike & zero_points2=nullptr, const EsTensorLike & beta=nullptr, float epsilon=0.000001, bool div_mode=true, int64_t dst_type=2) {
  auto *owner_graph_builder = ResolveBuilder(x, gamma, scales1, scales2, zero_points1, zero_points2, beta);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsRmsNormQuantV2(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), gamma.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scales1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scales2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), zero_points1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), zero_points2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), beta.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), epsilon, div_mode, dst_type);
  return {out.y1, out.y2};
}
}  // namespace es
}  // namespace ge
#endif
