/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_SwigluMxQuant_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_SwigluMxQuant_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_SwigluMxQuant_c.h"
namespace ge {
namespace es {

struct SwigluMxQuantOutput {
  EsTensorHolder y;
  EsTensorHolder mxscale;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   group_index
 */
inline SwigluMxQuantOutput SwigluMxQuant(const EsTensorLike & x, const EsTensorLike & group_index=nullptr, int64_t activate_dim=-1, bool activate_left=false, int64_t swiglu_mode=0, float clamp_limit=7.000000, float glu_alpha=1.702000, float glu_bias=1.000000, int64_t group_mode=0, int64_t axis=-1, int64_t dst_type=40, const char * round_mode="rint", int64_t scale_alg=0, float max_dtype_value=0.000000) {
  auto *owner_graph_builder = ResolveBuilder(x, group_index);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsSwigluMxQuant(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), group_index.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), activate_dim, activate_left, swiglu_mode, clamp_limit, glu_alpha, glu_bias, group_mode, axis, dst_type, round_mode, scale_alg, max_dtype_value);
  return {out.y, out.mxscale};
}
}  // namespace es
}  // namespace ge
#endif
