/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_SyncBatchNormGatherStats_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_SyncBatchNormGatherStats_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_SyncBatchNormGatherStats_c.h"
namespace ge {
namespace es {

struct SyncBatchNormGatherStatsOutput {
  EsTensorHolder batch_mean;
  EsTensorHolder batch_invstd;
  EsTensorHolder ref_mean;
  EsTensorHolder ref_variance;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   total_sum
 *   total_square_sum
 *   sample_count
 *   mean
 *   variance
 */
inline SyncBatchNormGatherStatsOutput SyncBatchNormGatherStats(const EsTensorLike & total_sum, const EsTensorLike & total_square_sum, const EsTensorLike & sample_count, const EsTensorLike & mean, const EsTensorLike & variance, float momentum=0.100000, float eps=0.000010) {
  auto *owner_graph_builder = ResolveBuilder(total_sum, total_square_sum, sample_count, mean, variance);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsSyncBatchNormGatherStats(total_sum.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), total_square_sum.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), sample_count.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mean.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), variance.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), momentum, eps);
  return {out.batch_mean, out.batch_invstd, out.ref_mean, out.ref_variance};
}
}  // namespace es
}  // namespace ge
#endif
