/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_SparseSlice_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_SparseSlice_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_SparseSlice_c.h"
namespace ge {
namespace es {

struct SparseSliceOutput {
  EsTensorHolder y_indices;
  EsTensorHolder y_values;
  EsTensorHolder y_shape;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   indices
 *   values
 *   shape
 *   start
 *   size
 */
inline SparseSliceOutput SparseSlice(const EsTensorLike & indices, const EsTensorLike & values, const EsTensorLike & shape, const EsTensorLike & start, const EsTensorLike & size) {
  auto *owner_graph_builder = ResolveBuilder(indices, values, shape, start, size);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsSparseSlice(indices.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), values.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), shape.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), start.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), size.ToTensorHolder(owner_graph_builder).GetCTensorHolder());
  return {out.y_indices, out.y_values, out.y_shape};
}
}  // namespace es
}  // namespace ge
#endif
