/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_SparseTensorDenseMatMul_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_SparseTensorDenseMatMul_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_SparseTensorDenseMatMul_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x1_indices
 *   x1_values
 *   x1_shape
 *   x2
 */
inline EsTensorHolder SparseTensorDenseMatMul(const EsTensorLike & x1_indices, const EsTensorLike & x1_values, const EsTensorLike & x1_shape, const EsTensorLike & x2, bool adjoint_a=false, bool adjoint_b=false) {
  auto *owner_graph_builder = ResolveBuilder(x1_indices, x1_values, x1_shape, x2);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsSparseTensorDenseMatMul(x1_indices.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x1_values.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x1_shape.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), adjoint_a, adjoint_b);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
