/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_SyncBatchNormBackwardReduce_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_SyncBatchNormBackwardReduce_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_SyncBatchNormBackwardReduce_c.h"
namespace ge {
namespace es {

struct SyncBatchNormBackwardReduceOutput {
  EsTensorHolder sum_dy_xmu;
  EsTensorHolder y;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   sum_dy
 *   sum_dy_dx_pad
 *   mean
 *   invert_std
 */
inline SyncBatchNormBackwardReduceOutput SyncBatchNormBackwardReduce(const EsTensorLike & sum_dy, const EsTensorLike & sum_dy_dx_pad, const EsTensorLike & mean, const EsTensorLike & invert_std) {
  auto *owner_graph_builder = ResolveBuilder(sum_dy, sum_dy_dx_pad, mean, invert_std);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsSyncBatchNormBackwardReduce(sum_dy.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), sum_dy_dx_pad.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mean.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), invert_std.ToTensorHolder(owner_graph_builder).GetCTensorHolder());
  return {out.sum_dy_xmu, out.y};
}
}  // namespace es
}  // namespace ge
#endif
