/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ScatterList_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ScatterList_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_ScatterList_c.h"
namespace ge {
namespace es {

/**
 * @note user needs to provide following inputs for dynamic output numbers:
 *   ref_var_num: dynamic output number of var
 */
inline std::vector<EsTensorHolder> ScatterList(const std::vector<EsTensorHolder> & var, const EsTensorLike & indice, const EsTensorLike & updates, const EsTensorLike & mask, int64_t ref_var_num, const char * reduce="update", int64_t axis=-2) {
  auto *owner_graph_builder = ResolveBuilder(var, indice, updates, mask);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto esb_var = TensorsToEsCTensorHolders(var);
  auto out = EsScatterList(esb_var.data(), static_cast<int64_t>(esb_var.size()), indice.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), updates.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), mask.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), ref_var_num, reduce, axis);
  std::vector<EsTensorHolder> ref_var_dynamic_outs;
  ref_var_dynamic_outs.reserve(out.ref_var_num);
  for (int64_t dyn_idx = 0; dyn_idx < out.ref_var_num; ++dyn_idx) {
    ref_var_dynamic_outs.emplace_back(out.ref_var[dyn_idx]);
  }
  return {ref_var_dynamic_outs};
}
}  // namespace es
}  // namespace ge
#endif
