/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_TransposeBatchMatMul_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_TransposeBatchMatMul_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_TransposeBatchMatMul_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x1
 *   x2
 *   bias
 *   scale
 */
inline EsTensorHolder TransposeBatchMatMul(const EsTensorLike & x1, const EsTensorLike & x2, const EsTensorLike & bias=nullptr, const EsTensorLike & scale=nullptr, const std::vector<int64_t> & perm_x1={}, const std::vector<int64_t> & perm_x2={}, const std::vector<int64_t> & perm_y={}, bool enable_hf32=false, int64_t batch_split_factor=1) {
  auto *owner_graph_builder = ResolveBuilder(x1, x2, bias, scale);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsTransposeBatchMatMul(x1.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), x2.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bias.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), perm_x1.data(), static_cast<int64_t>(perm_x1.size()), perm_x2.data(), static_cast<int64_t>(perm_x2.size()), perm_y.data(), static_cast<int64_t>(perm_y.size()), enable_hf32, batch_split_factor);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
