/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_TopKTopPSampleV2_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_TopKTopPSampleV2_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_TopKTopPSampleV2_c.h"
namespace ge {
namespace es {

struct TopKTopPSampleV2Output {
  EsTensorHolder logits_select_idx;
  EsTensorHolder logits_top_kp_select;
  EsTensorHolder logits_idx;
  EsTensorHolder logits_sort_masked;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   logits
 *   top_k
 *   top_p
 *   q
 *   min_ps
 */
inline TopKTopPSampleV2Output TopKTopPSampleV2(const EsTensorLike & logits, const EsTensorLike & top_k, const EsTensorLike & top_p, const EsTensorLike & q=nullptr, const EsTensorLike & min_ps=nullptr, float eps=0.000000, bool is_need_logits=false, int64_t top_k_guess=32, int64_t ks_max=1024, bool input_is_logits=true, bool is_need_sample_result=false) {
  auto *owner_graph_builder = ResolveBuilder(logits, top_k, top_p, q, min_ps);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsTopKTopPSampleV2(logits.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), top_k.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), top_p.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), q.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), min_ps.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), eps, is_need_logits, top_k_guess, ks_max, input_is_logits, is_need_sample_result);
  return {out.logits_select_idx, out.logits_top_kp_select, out.logits_idx, out.logits_sort_masked};
}
}  // namespace es
}  // namespace ge
#endif
