/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_WeightQuantBatchMatmulV2_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_WeightQuantBatchMatmulV2_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_WeightQuantBatchMatmulV2_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   x
 *   weight
 *   antiquant_scale
 *   antiquant_offset
 *   quant_scale
 *   quant_offset
 *   bias
 */
inline EsTensorHolder WeightQuantBatchMatmulV2(const EsTensorLike & x, const EsTensorLike & weight, const EsTensorLike & antiquant_scale, const EsTensorLike & antiquant_offset=nullptr, const EsTensorLike & quant_scale=nullptr, const EsTensorLike & quant_offset=nullptr, const EsTensorLike & bias=nullptr, bool transpose_x=false, bool transpose_weight=false, int64_t antiquant_group_size=0, int64_t dtype=-1, int64_t inner_precise=0) {
  auto *owner_graph_builder = ResolveBuilder(x, weight, antiquant_scale, antiquant_offset, quant_scale, quant_offset, bias);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsWeightQuantBatchMatmulV2(x.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), weight.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), antiquant_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), antiquant_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), quant_offset.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bias.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), transpose_x, transpose_weight, antiquant_group_size, dtype, inner_precise);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
