/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_HansEncode_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_HansEncode_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_HansEncode_c.h"
namespace ge {
namespace es {

struct HansEncodeOutput {
  EsTensorHolder ref_pdf;
  EsTensorHolder mantissa;
  EsTensorHolder fixed;
  EsTensorHolder var;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   input_tensor
 *   pdf
 */
inline HansEncodeOutput HansEncode(const EsTensorLike & input_tensor, const EsTensorLike & pdf, bool statistic=false, bool reshuff=false) {
  auto *owner_graph_builder = ResolveBuilder(input_tensor, pdf);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsHansEncode(input_tensor.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), pdf.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), statistic, reshuff);
  return {out.ref_pdf, out.mantissa, out.fixed, out.var};
}
}  // namespace es
}  // namespace ge
#endif
