/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_Im2col_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_Im2col_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_Im2col_c.h"
namespace ge {
namespace es {

inline EsTensorHolder Im2col(const EsTensorHolder & x, const std::vector<int64_t> & ksizes, const std::vector<int64_t> & strides={1}, const std::vector<int64_t> & dilations={1}, const char * padding_mode="CALCULATED", const std::vector<int64_t> & pads={0}) {
  auto out = EsIm2col(x.GetCTensorHolder(), ksizes.data(), static_cast<int64_t>(ksizes.size()), strides.data(), static_cast<int64_t>(strides.size()), dilations.data(), static_cast<int64_t>(dilations.size()), padding_mode, pads.data(), static_cast<int64_t>(pads.size()));
  return out;
}
}  // namespace es
}  // namespace ge
#endif
