/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_StridedSliceAssign_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_StridedSliceAssign_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_StridedSliceAssign_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   var
 *   begin
 *   end
 *   strides
 *   input_value
 */
inline EsTensorHolder StridedSliceAssign(const EsTensorLike & var, const EsTensorLike & begin, const EsTensorLike & end, const EsTensorLike & strides, const EsTensorLike & input_value, int64_t begin_mask=0, int64_t end_mask=0, int64_t ellipsis_mask=0, int64_t new_axis_mask=0, int64_t shrink_axis_mask=0) {
  auto *owner_graph_builder = ResolveBuilder(var, begin, end, strides, input_value);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsStridedSliceAssign(var.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), begin.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), end.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), strides.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), input_value.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
