/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_BatchMultiClassNonMaxSuppression_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_BatchMultiClassNonMaxSuppression_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_BatchMultiClassNonMaxSuppression_c.h"
namespace ge {
namespace es {

struct BatchMultiClassNonMaxSuppressionOutput {
  EsTensorHolder nmsed_boxes;
  EsTensorHolder nmsed_scores;
  EsTensorHolder nmsed_classes;
  EsTensorHolder nmsed_num;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   boxes
 *   scores
 *   clip_window
 *   num_valid_boxes
 */
inline BatchMultiClassNonMaxSuppressionOutput BatchMultiClassNonMaxSuppression(const EsTensorLike & boxes, const EsTensorLike & scores, const EsTensorLike & clip_window, const EsTensorLike & num_valid_boxes, float score_threshold, float iou_threshold, int64_t max_size_per_class, int64_t max_total_size, bool change_coordinate_frame=false, bool transpose_box=false, const std::vector<int64_t> & image_size={}) {
  auto *owner_graph_builder = ResolveBuilder(boxes, scores, clip_window, num_valid_boxes);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsBatchMultiClassNonMaxSuppression(boxes.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scores.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), clip_window.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), num_valid_boxes.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), score_threshold, iou_threshold, max_size_per_class, max_total_size, change_coordinate_frame, transpose_box, image_size.data(), static_cast<int64_t>(image_size.size()));
  return {out.nmsed_boxes, out.nmsed_scores, out.nmsed_classes, out.nmsed_num};
}
}  // namespace es
}  // namespace ge
#endif
