/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/
#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_cv_OPS_CPP_H
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_cv_OPS_CPP_H


/** Unsupported ops and reasons: 
 */
#include "es_AdjustSaturation.h"
#include "es_Aipp.h"
#include "es_BackgroundReplace.h"
#include "es_BatchMultiClassNonMaxSuppression.h"
#include "es_BlendImagesCustom.h"
#include "es_BoundingBoxDecode.h"
#include "es_BoundingBoxEncode.h"
#include "es_CheckValid.h"
#include "es_Col2ImV2.h"
#include "es_CombinedNonMaxSuppression.h"
#include "es_CropAndResize.h"
#include "es_DIoU.h"
#include "es_DecodeBboxV2.h"
#include "es_Dilation2D.h"
#include "es_Dilation2DBackpropFilter.h"
#include "es_Dilation2DBackpropInput.h"
#include "es_ExtractImagePatches.h"
#include "es_GIoU.h"
#include "es_GenerateBoundingBoxProposals.h"
#include "es_GridSample.h"
#include "es_GridSampler2D.h"
#include "es_GridSampler2DGrad.h"
#include "es_GridSampler3DGrad.h"
#include "es_GridUnnormal.h"
#include "es_IMGWarpOffsets.h"
#include "es_IMGWarpResize.h"
#include "es_ImageProjectiveTransform.h"
#include "es_ImageProjectiveTransformV2.h"
#include "es_Iou3D.h"
#include "es_IouV2.h"
#include "es_LUT3D.h"
#include "es_MrgbaCustom.h"
#include "es_NMSWithMask.h"
#include "es_NonMaxSuppressionV3.h"
#include "es_NonMaxSuppressionV4.h"
#include "es_NonMaxSuppressionV7.h"
#include "es_NormalizeBBox.h"
#include "es_ROIAlignGrad.h"
#include "es_Resize.h"
#include "es_ResizeBicubicV2.h"
#include "es_ResizeBicubicV2Grad.h"
#include "es_ResizeBilinearV2.h"
#include "es_ResizeBilinearV2Grad.h"
#include "es_ResizeD.h"
#include "es_ResizeGradD.h"
#include "es_ResizeLinear.h"
#include "es_ResizeLinearGrad.h"
#include "es_ResizeNearestNeighborV2.h"
#include "es_ResizeNearestNeighborV2Grad.h"
#include "es_ResizeTrilinear.h"
#include "es_RoiAlignRotated.h"
#include "es_RoiExtractor.h"
#include "es_RotatedBoxDecode.h"
#include "es_RotatedBoxEncode.h"
#include "es_RotatedIou.h"
#include "es_RotatedOverlaps.h"
#include "es_RpnProposals.h"
#include "es_ScaleAndTranslate.h"
#include "es_SortedNMS.h"
#include "es_SpatialTransformer.h"
#include "es_StackGroupPoints.h"
#include "es_ToAbsoluteBBox.h"
#include "es_TransArgb.h"
#include "es_UpsampleNearest3d.h"
#include "es_UpsampleNearest3dGrad.h"
#include "es_UpsampleNearestExact3d.h"
#include "es_UpsampleNearestExact3dGrad.h"
#include "es_YoloPreDetection.h"
#include "es_YoloxBoundingBoxDecode.h"
#endif  // AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_cv_OPS_CPP_H
