/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_GenerateBoundingBoxProposals_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_GenerateBoundingBoxProposals_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_GenerateBoundingBoxProposals_c.h"
namespace ge {
namespace es {

struct GenerateBoundingBoxProposalsOutput {
  EsTensorHolder rois;
  EsTensorHolder rois_probabilities;
};
/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   scores
 *   bbox_deltas
 *   image_info
 *   anchors
 *   nms_threshold
 *   pre_nms_topn
 *   min_size
 */
inline GenerateBoundingBoxProposalsOutput GenerateBoundingBoxProposals(const EsTensorLike & scores, const EsTensorLike & bbox_deltas, const EsTensorLike & image_info, const EsTensorLike & anchors, const EsTensorLike & nms_threshold, const EsTensorLike & pre_nms_topn, const EsTensorLike & min_size, int64_t post_nms_topn=300) {
  auto *owner_graph_builder = ResolveBuilder(scores, bbox_deltas, image_info, anchors, nms_threshold, pre_nms_topn, min_size);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsGenerateBoundingBoxProposals(scores.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), bbox_deltas.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), image_info.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), anchors.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), nms_threshold.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), pre_nms_topn.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), min_size.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), post_nms_topn);
  return {out.rois, out.rois_probabilities};
}
}  // namespace es
}  // namespace ge
#endif
