/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_NonMaxSuppressionV3_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_NonMaxSuppressionV3_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_NonMaxSuppressionV3_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   boxes
 *   scores
 *   max_output_size
 *   iou_threshold
 *   score_threshold
 */
inline EsTensorHolder NonMaxSuppressionV3(const EsTensorLike & boxes, const EsTensorLike & scores, const EsTensorLike & max_output_size, const EsTensorLike & iou_threshold, const EsTensorLike & score_threshold, int64_t offset=0) {
  auto *owner_graph_builder = ResolveBuilder(boxes, scores, max_output_size, iou_threshold, score_threshold);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsNonMaxSuppressionV3(boxes.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scores.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), max_output_size.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), iou_threshold.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), score_threshold.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), offset);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
