/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_RoiExtractor_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_RoiExtractor_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_RoiExtractor_c.h"
namespace ge {
namespace es {

inline EsTensorHolder RoiExtractor(const std::vector<EsTensorHolder> & features, const EsTensorLike & rois, const EsTensorLike & index=nullptr, int64_t finest_scale=56, float roi_scale_factor=0.000000, const std::vector<float> & spatial_scale={0.250000, 0.125000, 0.062500, 0.031250}, int64_t pooled_height=7, int64_t pooled_width=7, int64_t sample_num=0, const char * pool_mode="avg", bool aligned=true) {
  auto *owner_graph_builder = ResolveBuilder(features, rois, index);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto esb_features = TensorsToEsCTensorHolders(features);
  auto out = EsRoiExtractor(esb_features.data(), static_cast<int64_t>(esb_features.size()), rois.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), index.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), finest_scale, roi_scale_factor, spatial_scale.data(), static_cast<int64_t>(spatial_scale.size()), pooled_height, pooled_width, sample_num, pool_mode, aligned);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
