/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ResizeD_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ResizeD_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_ResizeD_c.h"
namespace ge {
namespace es {

inline EsTensorHolder ResizeD(const EsTensorHolder & x, const std::vector<int64_t> & sizes, const std::vector<float> & scales={}, const std::vector<int64_t> & roi={}, const char * coordinate_transformation_mode="half_pixel", float cubic_coeff_a=-0.750000, int64_t exclude_outside=0, float extrapolation_value=0.000000, const char * mode="nearest", const char * nearest_mode="round_prefer_floor", const char * data_format="NCHW") {
  auto out = EsResizeD(x.GetCTensorHolder(), sizes.data(), static_cast<int64_t>(sizes.size()), scales.data(), static_cast<int64_t>(scales.size()), roi.data(), static_cast<int64_t>(roi.size()), coordinate_transformation_mode, cubic_coeff_a, exclude_outside, extrapolation_value, mode, nearest_mode, data_format);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
