/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ScaleAndTranslate_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_ScaleAndTranslate_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_tensor_like.h"
#include "es_log.h"
#include <iostream>
#include "es_ScaleAndTranslate_c.h"
namespace ge {
namespace es {

/**
 * @note at least one of the following input arguments should be EsTensorHolder object:
 *   images
 *   size
 *   scale
 *   translation
 */
inline EsTensorHolder ScaleAndTranslate(const EsTensorLike & images, const EsTensorLike & size, const EsTensorLike & scale, const EsTensorLike & translation, const char * kernel_type="lanczos3", bool antialias=true) {
  auto *owner_graph_builder = ResolveBuilder(images, size, scale, translation);
  ES_ASSERT_NOTNULL(owner_graph_builder, "Failed to resolve owner builder: please ensure at least one input tensor or an explicit owner_builder is provided when supported.");
  auto out = EsScaleAndTranslate(images.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), size.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), scale.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), translation.ToTensorHolder(owner_graph_builder).GetCTensorHolder(), kernel_type, antialias);
  return out;
}
}  // namespace es
}  // namespace ge
#endif
