/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_YoloPreDetection_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_YoloPreDetection_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_YoloPreDetection_c.h"
namespace ge {
namespace es {

struct YoloPreDetectionOutput {
  EsTensorHolder coord_data;
  EsTensorHolder obj_prob;
  EsTensorHolder classes_prob;
};
inline YoloPreDetectionOutput YoloPreDetection(const EsTensorHolder & x, int64_t boxes=3, int64_t coords=4, int64_t classes=80, const char * yolo_version="V5", bool softmax=false, bool background=false, bool softmaxtree=false) {
  auto out = EsYoloPreDetection(x.GetCTensorHolder(), boxes, coords, classes, yolo_version, softmax, background, softmaxtree);
  return {out.coord_data, out.obj_prob, out.classes_prob};
}
}  // namespace es
}  // namespace ge
#endif
