/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_hccl_OPS_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_hccl_OPS_H_
#ifdef __cplusplus
extern "C" {
#endif

/** Unsupported ops and reasons: 
 */
#include "es_HcomAllGather_c.h"
#include "es_HcomAllGatherV_c.h"
#include "es_HcomAllReduce_c.h"
#include "es_HcomAllToAll_c.h"
#include "es_HcomAllToAllV_c.h"
#include "es_HcomAllToAllVC_c.h"
#include "es_HcomBroadcast_c.h"
#include "es_HcomReceive_c.h"
#include "es_HcomReduce_c.h"
#include "es_HcomReduceScatter_c.h"
#include "es_HcomReduceScatterV_c.h"
#include "es_HcomSend_c.h"

#ifdef __cplusplus
}
#endif
#endif
