/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/
#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_hccl_OPS_CPP_H
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_hccl_OPS_CPP_H


/** Unsupported ops and reasons: 
 */
#include "es_HcomAllGather.h"
#include "es_HcomAllGatherV.h"
#include "es_HcomAllReduce.h"
#include "es_HcomAllToAll.h"
#include "es_HcomAllToAllV.h"
#include "es_HcomAllToAllVC.h"
#include "es_HcomBroadcast.h"
#include "es_HcomReceive.h"
#include "es_HcomReduce.h"
#include "es_HcomReduceScatter.h"
#include "es_HcomReduceScatterV.h"
#include "es_HcomSend.h"
#endif  // AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_hccl_OPS_CPP_H
