/* Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This file is a part of the CANN Open Software.
 * Licensed under CANN Open Software License Agreement Version 1.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * ===================================================================================================================*/

/*********************************************************************************************************************
 This file is GENERATED by bin/gen_esb, do not edit it manually
*********************************************************************************************************************/

#ifndef AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_HcomReceive_CPP_H_
#define AIR_CXX_COMPILER_GRAPH_EAGER_STYLE_GRAPH_BUILDER_OP_HcomReceive_CPP_H_
#include <utility>
#include "es_tensor_holder.h"
#include "es_graph_builder.h"
#include "es_HcomReceive_c.h"
namespace ge {
namespace es {

inline EsTensorHolder HcomReceive(const EsGraphBuilder & owner_builder, const char * group, int64_t sr_tag, int64_t src_rank, const std::vector<int64_t> & shape, ge::DataType dtype) {
  auto out = EsHcomReceive(owner_builder.GetCGraphBuilder(), group, sr_tag, src_rank, shape.data(), static_cast<int64_t>(shape.size()), static_cast<C_DataType>(dtype));
  return out;
}
}  // namespace es
}  // namespace ge
#endif
